// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachment_library.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMaliciousHashes = `-- name: ListMaliciousHashes :many
SELECT
    id,
    sha256,
    risk_score,
    threat_tags
FROM attachment_library
WHERE is_malicious = TRUE
  AND deleted_at IS NULL
`

type ListMaliciousHashesRow struct {
	ID         int64       `db:"id" json:"id"`
	Sha256     string      `db:"sha256" json:"sha256"`
	RiskScore  pgtype.Int4 `db:"risk_score" json:"risk_score"`
	ThreatTags []string    `db:"threat_tags" json:"threat_tags"`
}

// Returns all malicious hashes for populating the TI hash cache.
func (q *Queries) ListMaliciousHashes(ctx context.Context) ([]ListMaliciousHashesRow, error) {
	rows, err := q.db.Query(ctx, listMaliciousHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaliciousHashesRow
	for rows.Next() {
		var i ListMaliciousHashesRow
		if err := rows.Scan(
			&i.ID,
			&i.Sha256,
			&i.RiskScore,
			&i.ThreatTags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMalwareHash = `-- name: UpsertMalwareHash :exec
INSERT INTO attachment_library (sha256, is_malicious, risk_score, threat_tags)
VALUES ($1, TRUE, $2, $3)
ON CONFLICT (sha256)
DO UPDATE
SET
    is_malicious = TRUE,
    risk_score   = GREATEST(attachment_library.risk_score, EXCLUDED.risk_score),
    threat_tags  = (
        SELECT ARRAY(
            SELECT DISTINCT tag
            FROM unnest(
                COALESCE(attachment_library.threat_tags, '{}'::TEXT[]) ||
                COALESCE(EXCLUDED.threat_tags, '{}'::TEXT[])
            ) AS tag
            WHERE tag IS NOT NULL
              AND btrim(tag) <> ''
            ORDER BY tag
        )
    ),
    updated_at   = NOW()
`

type UpsertMalwareHashParams struct {
	Sha256     string      `db:"sha256" json:"sha256"`
	RiskScore  pgtype.Int4 `db:"risk_score" json:"risk_score"`
	ThreatTags []string    `db:"threat_tags" json:"threat_tags"`
}

// Upserts a malware hash into the attachment_library table.
// ON CONFLICT (sha256): set is_malicious = TRUE, take GREATEST risk_score,
// merge threat_tags (union, distinct, sorted), touch updated_at.
func (q *Queries) UpsertMalwareHash(ctx context.Context, arg UpsertMalwareHashParams) error {
	_, err := q.db.Exec(ctx, upsertMalwareHash, arg.Sha256, arg.RiskScore, arg.ThreatTags)
	return err
}
