// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_reads.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :many

SELECT
    id,
    org_id,
    user_id,
    name,
    key_prefix,
    key_hash,
    scopes,
    last_used_at,
    expires_at,
    revoked_at
FROM api_keys
WHERE key_prefix = $1
`

type GetAPIKeyByPrefixRow struct {
	ID         int64              `db:"id" json:"id"`
	OrgID      int64              `db:"org_id" json:"org_id"`
	UserID     pgtype.Int8        `db:"user_id" json:"user_id"`
	Name       string             `db:"name" json:"name"`
	KeyPrefix  string             `db:"key_prefix" json:"key_prefix"`
	KeyHash    string             `db:"key_hash" json:"key_hash"`
	Scopes     []string           `db:"scopes" json:"scopes"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

// =============================================================================
// auth_reads.sql — identity / tenancy reads for SVC-01 ingestion + auth layer
// =============================================================================
// These read the control-plane tables (api_keys, users, organisations) that
// resolve the tenant BEFORE org context exists, so they are NOT subject to the
// app.current_org_id GUC. audit_log reads are operator-facing.
// =============================================================================
// Resolves candidate API keys by their stored lookup prefix (api_keys.key_prefix
// — the leading fragment of the plaintext key produced by shared/auth
// KeyManager.LookupPrefix). api_keys.key_hash is a *salted bcrypt* hash, so a
// presented key can NEVER be matched by hash equality; the caller fetches the
// candidate row(s) by their indexed prefix and then bcrypt-compares the presented
// key against each key_hash (shared/auth ValidateKey). A prefix is selective but
// not guaranteed unique, so this returns :many. Callers MUST still reject a key
// whose revoked_at is set or whose expires_at is in the past.
func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) ([]GetAPIKeyByPrefixRow, error) {
	rows, err := q.db.Query(ctx, getAPIKeyByPrefix, keyPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAPIKeyByPrefixRow
	for rows.Next() {
		var i GetAPIKeyByPrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganisationByID = `-- name: GetOrganisationByID :one
SELECT id, name, slug, monthly_ingestion_limit, deleted_at, created_at, updated_at, notification_threshold, notification_channels, retention_days
FROM organisations
WHERE id = $1
  AND deleted_at IS NULL
`

// Reads an organisation by id, including ingestion limit and notification
// config. Soft-deleted orgs are excluded.
func (q *Queries) GetOrganisationByID(ctx context.Context, id int64) (Organisation, error) {
	row := q.db.QueryRow(ctx, getOrganisationByID, id)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.MonthlyIngestionLimit,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NotificationThreshold,
		&i.NotificationChannels,
		&i.RetentionDays,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    org_id,
    email,
    display_name,
    role,
    last_login_at,
    created_at
FROM users
WHERE org_id = $1
  AND email = $2
  AND deleted_at IS NULL
`

type GetUserByEmailParams struct {
	OrgID int64  `db:"org_id" json:"org_id"`
	Email string `db:"email" json:"email"`
}

type GetUserByEmailRow struct {
	ID          int64              `db:"id" json:"id"`
	OrgID       int64              `db:"org_id" json:"org_id"`
	Email       string             `db:"email" json:"email"`
	DisplayName pgtype.Text        `db:"display_name" json:"display_name"`
	Role        UserRole           `db:"role" json:"role"`
	LastLoginAt pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Reads a user by (org_id, email) for login. Soft-deleted users are excluded.
func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.OrgID, arg.Email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmailWithPassword = `-- name: GetUserByEmailWithPassword :one
SELECT
    id,
    org_id,
    email,
    display_name,
    role,
    password_hash,
    last_login_at,
    created_at
FROM users
WHERE org_id = $1
  AND email = $2
  AND deleted_at IS NULL
`

type GetUserByEmailWithPasswordParams struct {
	OrgID int64  `db:"org_id" json:"org_id"`
	Email string `db:"email" json:"email"`
}

type GetUserByEmailWithPasswordRow struct {
	ID           int64              `db:"id" json:"id"`
	OrgID        int64              `db:"org_id" json:"org_id"`
	Email        string             `db:"email" json:"email"`
	DisplayName  pgtype.Text        `db:"display_name" json:"display_name"`
	Role         UserRole           `db:"role" json:"role"`
	PasswordHash pgtype.Text        `db:"password_hash" json:"password_hash"`
	LastLoginAt  pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Reads a user by (org_id, email) INCLUDING password_hash, for the svc-10
// dashboard login flow (POST /api/v1/auth/login). GetUserByEmail deliberately
// omits password_hash; this variant returns it so the handler can bcrypt-compare
// the presented password against the stored hash. password_hash is NULLABLE
// (users may be created without a local password); the caller MUST reject a NULL
// hash and never leak which credential field was wrong (generic 401). users is a
// control-plane table and is NOT RLS-forced, so the org_id predicate is the
// tenant boundary. Soft-deleted users are excluded.
func (q *Queries) GetUserByEmailWithPassword(ctx context.Context, arg GetUserByEmailWithPasswordParams) (GetUserByEmailWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailWithPassword, arg.OrgID, arg.Email)
	var i GetUserByEmailWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    org_id,
    email,
    display_name,
    role,
    last_login_at,
    created_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID          int64              `db:"id" json:"id"`
	OrgID       int64              `db:"org_id" json:"org_id"`
	Email       string             `db:"email" json:"email"`
	DisplayName pgtype.Text        `db:"display_name" json:"display_name"`
	Role        UserRole           `db:"role" json:"role"`
	LastLoginAt pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Reads a user by id. Soft-deleted users are excluded.
func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogForOrg = `-- name: ListAuditLogForOrg :many
SELECT
    id,
    org_id,
    user_id,
    api_key_id,
    action,
    entity_type,
    entity_id,
    diff,
    ip_address,
    created_at
FROM audit_log
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogForOrgParams struct {
	OrgID  int64 `db:"org_id" json:"org_id"`
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListAuditLogForOrgRow struct {
	ID         int64              `db:"id" json:"id"`
	OrgID      int64              `db:"org_id" json:"org_id"`
	UserID     pgtype.Int8        `db:"user_id" json:"user_id"`
	ApiKeyID   pgtype.Int8        `db:"api_key_id" json:"api_key_id"`
	Action     string             `db:"action" json:"action"`
	EntityType NullEntityTypeEnum `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.Int8        `db:"entity_id" json:"entity_id"`
	Diff       []byte             `db:"diff" json:"diff"`
	IpAddress  *netip.Addr        `db:"ip_address" json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Operator-facing audit trail for an organisation, newest first.
func (q *Queries) ListAuditLogForOrg(ctx context.Context, arg ListAuditLogForOrgParams) ([]ListAuditLogForOrgRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogForOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogForOrgRow
	for rows.Next() {
		var i ListAuditLogForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.ApiKeyID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Diff,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgAdmins = `-- name: ListOrgAdmins :many
SELECT
    id,
    email,
    display_name
FROM users
WHERE org_id = $1
  AND role = 'admin'
  AND deleted_at IS NULL
ORDER BY email
`

type ListOrgAdminsRow struct {
	ID          int64       `db:"id" json:"id"`
	Email       string      `db:"email" json:"email"`
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
}

// Admin contacts for an organisation, used by SVC-09 to address email alerts
// (ARCH-SPEC §1-step6a: "SELECT email, display_name FROM users WHERE org_id=?
// AND role='admin' AND deleted_at IS NULL"). users is a control-plane table and
// is NOT RLS-forced, so this read is not subject to the app.current_org_id GUC;
// the org_id filter is the tenant boundary. Ordered by email for a stable
// recipient list.
func (q *Queries) ListOrgAdmins(ctx context.Context, orgID int64) ([]ListOrgAdminsRow, error) {
	rows, err := q.db.Query(ctx, listOrgAdmins, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgAdminsRow
	for rows.Next() {
		var i ListOrgAdminsRow
		if err := rows.Scan(&i.ID, &i.Email, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1
`

// Records that an API key was used for a request.
func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}

const touchUserLastLogin = `-- name: TouchUserLastLogin :exec
UPDATE users
SET last_login_at = NOW()
WHERE id = $1
`

// Records that a user successfully authenticated (best-effort; off the login
// hot path). users is a control-plane table, not RLS-forced.
func (q *Queries) TouchUserLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchUserLastLogin, id)
	return err
}
