// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one

SELECT id, org_id, user_id, scopes, expires_at, revoked_at
FROM api_keys
WHERE key_hash = $1
`

type GetAPIKeyByHashRow struct {
	ID        int64              `db:"id" json:"id"`
	OrgID     int64              `db:"org_id" json:"org_id"`
	UserID    pgtype.Int8        `db:"user_id" json:"user_id"`
	Scopes    []string           `db:"scopes" json:"scopes"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

// =============================================================================
// auth.sql — shared authentication lookups (shared/auth package)
// =============================================================================
// Used by SVC-01 ingestion and SVC-10 API to authenticate API keys against the
// api_keys table. ARCH-SPEC §1 step 1, §14 step 1.
// =============================================================================
// Resolves an API key by its sha256 hash. The caller enforces revoked_at /
// expires_at; both are returned so a single round-trip covers validation.
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = NOW() WHERE id = $1
`

// Records that a key authenticated successfully (ARCH-SPEC: last_used_at must be
// updated on every successful key auth).
func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
