// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_reads.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one

SELECT
    id,
    org_id,
    user_id,
    name,
    key_prefix,
    scopes,
    last_used_at,
    expires_at,
    revoked_at
FROM api_keys
WHERE key_hash = $1
`

type GetAPIKeyByHashRow struct {
	ID         int64              `db:"id" json:"id"`
	OrgID      int64              `db:"org_id" json:"org_id"`
	UserID     pgtype.Int8        `db:"user_id" json:"user_id"`
	Name       string             `db:"name" json:"name"`
	KeyPrefix  string             `db:"key_prefix" json:"key_prefix"`
	Scopes     []string           `db:"scopes" json:"scopes"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

// =============================================================================
// auth_reads.sql — identity / tenancy reads for SVC-01 ingestion + auth layer
// =============================================================================
// These read the control-plane tables (api_keys, users, organisations) that
// resolve the tenant BEFORE org context exists, so they are NOT subject to the
// app.current_org_id GUC. audit_log reads are operator-facing.
// =============================================================================
// Resolves an API key by its stored hash for request authentication. Callers
// must still check expires_at / revoked_at against NOW() before trusting it.
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getOrganisationByID = `-- name: GetOrganisationByID :one
SELECT id, name, slug, monthly_ingestion_limit, deleted_at, created_at, updated_at, notification_threshold, notification_channels, retention_days
FROM organisations
WHERE id = $1
  AND deleted_at IS NULL
`

// Reads an organisation by id, including ingestion limit and notification
// config. Soft-deleted orgs are excluded.
func (q *Queries) GetOrganisationByID(ctx context.Context, id int64) (Organisation, error) {
	row := q.db.QueryRow(ctx, getOrganisationByID, id)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.MonthlyIngestionLimit,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NotificationThreshold,
		&i.NotificationChannels,
		&i.RetentionDays,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    org_id,
    email,
    display_name,
    role,
    last_login_at,
    created_at
FROM users
WHERE org_id = $1
  AND email = $2
  AND deleted_at IS NULL
`

type GetUserByEmailParams struct {
	OrgID int64  `db:"org_id" json:"org_id"`
	Email string `db:"email" json:"email"`
}

type GetUserByEmailRow struct {
	ID          int64              `db:"id" json:"id"`
	OrgID       int64              `db:"org_id" json:"org_id"`
	Email       string             `db:"email" json:"email"`
	DisplayName pgtype.Text        `db:"display_name" json:"display_name"`
	Role        UserRole           `db:"role" json:"role"`
	LastLoginAt pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Reads a user by (org_id, email) for login. Soft-deleted users are excluded.
func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.OrgID, arg.Email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    org_id,
    email,
    display_name,
    role,
    last_login_at,
    created_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID          int64              `db:"id" json:"id"`
	OrgID       int64              `db:"org_id" json:"org_id"`
	Email       string             `db:"email" json:"email"`
	DisplayName pgtype.Text        `db:"display_name" json:"display_name"`
	Role        UserRole           `db:"role" json:"role"`
	LastLoginAt pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Reads a user by id. Soft-deleted users are excluded.
func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogForOrg = `-- name: ListAuditLogForOrg :many
SELECT
    id,
    org_id,
    user_id,
    api_key_id,
    action,
    entity_type,
    entity_id,
    diff,
    ip_address,
    created_at
FROM audit_log
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogForOrgParams struct {
	OrgID  int64 `db:"org_id" json:"org_id"`
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListAuditLogForOrgRow struct {
	ID         int64              `db:"id" json:"id"`
	OrgID      int64              `db:"org_id" json:"org_id"`
	UserID     pgtype.Int8        `db:"user_id" json:"user_id"`
	ApiKeyID   pgtype.Int8        `db:"api_key_id" json:"api_key_id"`
	Action     string             `db:"action" json:"action"`
	EntityType NullEntityTypeEnum `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.Int8        `db:"entity_id" json:"entity_id"`
	Diff       []byte             `db:"diff" json:"diff"`
	IpAddress  *netip.Addr        `db:"ip_address" json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Operator-facing audit trail for an organisation, newest first.
func (q *Queries) ListAuditLogForOrg(ctx context.Context, arg ListAuditLogForOrgParams) ([]ListAuditLogForOrgRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogForOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogForOrgRow
	for rows.Next() {
		var i ListAuditLogForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.ApiKeyID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Diff,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1
`

// Records that an API key was used for a request.
func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
