// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: console_reads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentVerdictForEmail = `-- name: GetCurrentVerdictForEmail :one
SELECT
    entity_type,
    entity_id,
    label,
    confidence,
    source,
    model_version,
    notes,
    created_by,
    created_at
FROM current_verdicts
WHERE entity_type = 'email'
  AND entity_id = $1
`

// The current (most-recent) verdict for an email, from the current_verdicts view
// (DISTINCT ON (entity_type, entity_id) ORDER BY created_at DESC — migration
// 005). entity_type is pinned to 'email' and entity_id = emails.internal_id.
// The underlying verdicts table is RLS-forced, so this runs inside WithOrgTx.
// Returns no row when the email has no verdict yet.
func (q *Queries) GetCurrentVerdictForEmail(ctx context.Context, entityID int64) (CurrentVerdict, error) {
	row := q.db.QueryRow(ctx, getCurrentVerdictForEmail, entityID)
	var i CurrentVerdict
	err := row.Scan(
		&i.EntityType,
		&i.EntityID,
		&i.Label,
		&i.Confidence,
		&i.Source,
		&i.ModelVersion,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrichedThreatByID = `-- name: GetEnrichedThreatByID :one
SELECT id, url, domain, online, http_status_code, ip_address, cidr_block, asn, asn_name, isp, country, country_name, region, city, latitude, longitude, ssl_enabled, cert_issuer, cert_subject, cert_valid_from, cert_valid_to, cert_serial, tld, registrar, creation_date, expiry_date, updated_date, name_servers, page_language, page_title, threat_type, target_brand, threat_tags, source_feed, source_id, first_seen, last_seen, last_checked, notes, analysis_metadata, risk_score, deleted_at, created_at, updated_at, org_id, feed_id, is_global, brand_id
FROM enriched_threats
WHERE id = $1
  AND deleted_at IS NULL
`

// Reads one enriched_threats row (the TI / enrichment record an email_url points
// to via threat_id) for the URL-threat detail panel. enriched_threats is
// RLS-forced and its policy admits org-owned OR is_global rows, so this runs
// inside WithOrgTx. Soft-deleted rows are excluded. Returns no row when the
// threat_id is NULL/purged or hidden by the tenant boundary.
func (q *Queries) GetEnrichedThreatByID(ctx context.Context, id int64) (EnrichedThreat, error) {
	row := q.db.QueryRow(ctx, getEnrichedThreatByID, id)
	var i EnrichedThreat
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Domain,
		&i.Online,
		&i.HttpStatusCode,
		&i.IpAddress,
		&i.CidrBlock,
		&i.Asn,
		&i.AsnName,
		&i.Isp,
		&i.Country,
		&i.CountryName,
		&i.Region,
		&i.City,
		&i.Latitude,
		&i.Longitude,
		&i.SslEnabled,
		&i.CertIssuer,
		&i.CertSubject,
		&i.CertValidFrom,
		&i.CertValidTo,
		&i.CertSerial,
		&i.Tld,
		&i.Registrar,
		&i.CreationDate,
		&i.ExpiryDate,
		&i.UpdatedDate,
		&i.NameServers,
		&i.PageLanguage,
		&i.PageTitle,
		&i.ThreatType,
		&i.TargetBrand,
		&i.ThreatTags,
		&i.SourceFeed,
		&i.SourceID,
		&i.FirstSeen,
		&i.LastSeen,
		&i.LastChecked,
		&i.Notes,
		&i.AnalysisMetadata,
		&i.RiskScore,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.FeedID,
		&i.IsGlobal,
		&i.BrandID,
	)
	return i, err
}

const listRuleHitsForEmail = `-- name: ListRuleHitsForEmail :many
SELECT
    rh.id,
    rh.rule_id,
    rh.rule_version,
    rh.score_impact,
    rh.match_detail,
    rh.fired_at,
    r.name        AS rule_name,
    r.description AS rule_description,
    r.target      AS rule_target
FROM rule_hits rh
LEFT JOIN rules r ON r.id = rh.rule_id
WHERE rh.entity_type = 'email'
  AND rh.entity_id = $1
  AND rh.email_fetched_at = $2
ORDER BY rh.fired_at DESC, rh.id DESC
`

type ListRuleHitsForEmailParams struct {
	EntityID       int64              `db:"entity_id" json:"entity_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
}

type ListRuleHitsForEmailRow struct {
	ID              int64              `db:"id" json:"id"`
	RuleID          pgtype.Int8        `db:"rule_id" json:"rule_id"`
	RuleVersion     string             `db:"rule_version" json:"rule_version"`
	ScoreImpact     int32              `db:"score_impact" json:"score_impact"`
	MatchDetail     []byte             `db:"match_detail" json:"match_detail"`
	FiredAt         pgtype.Timestamptz `db:"fired_at" json:"fired_at"`
	RuleName        pgtype.Text        `db:"rule_name" json:"rule_name"`
	RuleDescription pgtype.Text        `db:"rule_description" json:"rule_description"`
	RuleTarget      pgtype.Text        `db:"rule_target" json:"rule_target"`
}

// Rule-firing history for an email (score explainability). Keyed on the
// polymorphic pointer (entity_type='email', entity_id=emails.internal_id) plus
// the partition's email_fetched_at. LEFT JOIN rules so the (possibly archived)
// rule's name/version/status/target surface alongside the denormalised
// point-in-time rule_version + score_impact snapshots on the hit row. rule_hits
// is RLS-forced (runs inside WithOrgTx); rules is RLS-forced too and is admitted
// by the same org GUC. A NULL rule_id (archived rule) leaves the joined rule
// columns NULL — the snapshot columns on the hit still explain the score.
func (q *Queries) ListRuleHitsForEmail(ctx context.Context, arg ListRuleHitsForEmailParams) ([]ListRuleHitsForEmailRow, error) {
	rows, err := q.db.Query(ctx, listRuleHitsForEmail, arg.EntityID, arg.EmailFetchedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRuleHitsForEmailRow
	for rows.Next() {
		var i ListRuleHitsForEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.RuleVersion,
			&i.ScoreImpact,
			&i.MatchDetail,
			&i.FiredAt,
			&i.RuleName,
			&i.RuleDescription,
			&i.RuleTarget,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesForOrg = `-- name: ListRulesForOrg :many
SELECT
    id,
    org_id,
    name,
    description,
    version,
    status,
    target,
    score_impact,
    created_at
FROM rules
WHERE (org_id = $1 OR org_id IS NULL)
ORDER BY id
`

type ListRulesForOrgRow struct {
	ID          int64              `db:"id" json:"id"`
	OrgID       pgtype.Int8        `db:"org_id" json:"org_id"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	Version     string             `db:"version" json:"version"`
	Status      RuleStatus         `db:"status" json:"status"`
	Target      string             `db:"target" json:"target"`
	ScoreImpact int32              `db:"score_impact" json:"score_impact"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Read-only rules list for the console (MVP-7: NO write/CRUD). Returns the org's
// rules plus platform-global rules (org_id IS NULL). NOTE: rules is RLS-forced
// and its tenant_isolation policy (migration 018) requires org_id IS NOT NULL
// AND org_id = current — so under RLS the global (org_id IS NULL) rules are NOT
// visible to this read; the (org_id = @org_id OR org_id IS NULL) form is kept for
// parity with ListActiveRulesForTargets, and the explicit org filter is the
// effective boundary. Ordered by id for a stable page.
func (q *Queries) ListRulesForOrg(ctx context.Context, orgID pgtype.Int8) ([]ListRulesForOrgRow, error) {
	rows, err := q.db.Query(ctx, listRulesForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRulesForOrgRow
	for rows.Next() {
		var i ListRulesForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.Status,
			&i.Target,
			&i.ScoreImpact,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerdictsForEmail = `-- name: ListVerdictsForEmail :many
SELECT
    id,
    label,
    confidence,
    source,
    model_version,
    notes,
    created_by,
    created_at
FROM verdicts
WHERE entity_type = 'email'
  AND entity_id = $1
  AND email_fetched_at = $2
ORDER BY created_at DESC, id DESC
`

type ListVerdictsForEmailParams struct {
	EntityID       int64              `db:"entity_id" json:"entity_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
}

type ListVerdictsForEmailRow struct {
	ID           int64              `db:"id" json:"id"`
	Label        VerdictLabel       `db:"label" json:"label"`
	Confidence   pgtype.Float8      `db:"confidence" json:"confidence"`
	Source       VerdictSource      `db:"source" json:"source"`
	ModelVersion pgtype.Text        `db:"model_version" json:"model_version"`
	Notes        pgtype.Text        `db:"notes" json:"notes"`
	CreatedBy    pgtype.Int8        `db:"created_by" json:"created_by"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Full append-only verdict history for an email, newest first, for the verdict
// timeline panel. entity_type='email', entity_id=emails.internal_id. The
// email_fetched_at predicate keeps the read inside the email's partition.
// verdicts is RLS-forced (runs inside WithOrgTx).
func (q *Queries) ListVerdictsForEmail(ctx context.Context, arg ListVerdictsForEmailParams) ([]ListVerdictsForEmailRow, error) {
	rows, err := q.db.Query(ctx, listVerdictsForEmail, arg.EntityID, arg.EmailFetchedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerdictsForEmailRow
	for rows.Next() {
		var i ListVerdictsForEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Confidence,
			&i.Source,
			&i.ModelVersion,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveEmailByEmailID = `-- name: ResolveEmailByEmailID :one

SELECT internal_id, fetched_at
FROM email_identities
WHERE org_id = $1
  AND email_id = $2
`

type ResolveEmailByEmailIDParams struct {
	OrgID   int64       `db:"org_id" json:"org_id"`
	EmailID pgtype.UUID `db:"email_id" json:"email_id"`
}

type ResolveEmailByEmailIDRow struct {
	InternalID int64              `db:"internal_id" json:"internal_id"`
	FetchedAt  pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
}

// =============================================================================
// console_reads.sql — read-only composite-detail queries for the svc-10
// analyst console (MVP-7). These back GET /api/v1/emails/{id} and the verdict /
// rule-hit explainability panels. All reads against RLS-forced tables (verdicts,
// rule_hits, enriched_threats) MUST run inside a tx that has set
// app.current_org_id (WithOrgTx). email_identities has NO RLS policy, so its
// read is scoped by the explicit org_id predicate.
// =============================================================================
// Maps the opaque logical UUIDv7 email_id (G5/G17) onto the canonical physical
// partition key (internal_id, fetched_at) via the email_identities dedup
// registry. email_identities is NOT RLS-forced, so the org_id predicate is the
// tenant boundary — a foreign tenant's email_id yields no row (fail-closed).
// Returns no row when the email_id was never registered (NULL-message_id emails
// and pre-035 rows are not resolvable by email_id).
func (q *Queries) ResolveEmailByEmailID(ctx context.Context, arg ResolveEmailByEmailIDParams) (ResolveEmailByEmailIDRow, error) {
	row := q.db.QueryRow(ctx, resolveEmailByEmailID, arg.OrgID, arg.EmailID)
	var i ResolveEmailByEmailIDRow
	err := row.Scan(&i.InternalID, &i.FetchedAt)
	return i, err
}
