// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_recipients.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEmailRecipient = `-- name: InsertEmailRecipient :one

INSERT INTO email_recipients (
    email_id,
    email_fetched_at,
    org_id,
    address,
    display_name,
    recipient_type
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id
`

type InsertEmailRecipientParams struct {
	EmailID        int64              `db:"email_id" json:"email_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
	OrgID          pgtype.Int8        `db:"org_id" json:"org_id"`
	Address        string             `db:"address" json:"address"`
	DisplayName    pgtype.Text        `db:"display_name" json:"display_name"`
	RecipientType  string             `db:"recipient_type" json:"recipient_type"`
}

// =============================================================================
// email_recipients.sql — to/cc/bcc recipients of a parsed email (SVC-02)
// =============================================================================
// recipient_type is constrained to ('to','cc','bcc'). org_id is set for RLS.
// =============================================================================
// Appends one recipient for an email by its composite partition key.
func (q *Queries) InsertEmailRecipient(ctx context.Context, arg InsertEmailRecipientParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEmailRecipient,
		arg.EmailID,
		arg.EmailFetchedAt,
		arg.OrgID,
		arg.Address,
		arg.DisplayName,
		arg.RecipientType,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listEmailRecipients = `-- name: ListEmailRecipients :many
SELECT id, address, display_name, recipient_type
FROM email_recipients
WHERE email_id = $1
  AND email_fetched_at = $2
ORDER BY id
`

type ListEmailRecipientsParams struct {
	EmailID        int64              `db:"email_id" json:"email_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
}

type ListEmailRecipientsRow struct {
	ID            int64       `db:"id" json:"id"`
	Address       string      `db:"address" json:"address"`
	DisplayName   pgtype.Text `db:"display_name" json:"display_name"`
	RecipientType string      `db:"recipient_type" json:"recipient_type"`
}

// Lists recipients for an email by composite partition key. org-scoped via RLS.
func (q *Queries) ListEmailRecipients(ctx context.Context, arg ListEmailRecipientsParams) ([]ListEmailRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listEmailRecipients, arg.EmailID, arg.EmailFetchedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailRecipientsRow
	for rows.Next() {
		var i ListEmailRecipientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.DisplayName,
			&i.RecipientType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
