// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_campaign_snapshot.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEmailCampaignSnapshot = `-- name: GetEmailCampaignSnapshot :one

SELECT
    e.campaign_id,
    COALESCE((c.analysis_metadata->>'email_count')::int, 0) AS email_count
FROM emails e
LEFT JOIN campaigns c
       ON c.id = e.campaign_id
      AND c.deleted_at IS NULL
WHERE e.internal_id = $1
  AND e.fetched_at = $2::timestamptz
`

type GetEmailCampaignSnapshotParams struct {
	InternalID int64              `db:"internal_id" json:"internal_id"`
	Column2    pgtype.Timestamptz `db:"column_2" json:"column_2"`
}

type GetEmailCampaignSnapshotRow struct {
	CampaignID pgtype.Int8 `db:"campaign_id" json:"campaign_id"`
	EmailCount interface{} `db:"email_count" json:"email_count"`
}

// =============================================================================
// email_campaign_snapshot.sql — campaign linkage lookup for dedupe replay
// =============================================================================
// Used by SVC-08 when a verdict row already exists for the same
// (entity_id, email_fetched_at) partition key and the engine needs to
// republish emails.verdict without recomputing campaign linkage.
// =============================================================================
// LEFT JOIN so dedupe replay still completes when the campaign was
// soft-deleted (deleted_at IS NOT NULL) or e.campaign_id is NULL on
// legacy rows. Republish prefers verdicts.kafka_verdict_wire, which
// does not need a live campaign row to be byte-stable.
func (q *Queries) GetEmailCampaignSnapshot(ctx context.Context, arg GetEmailCampaignSnapshotParams) (GetEmailCampaignSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getEmailCampaignSnapshot, arg.InternalID, arg.Column2)
	var i GetEmailCampaignSnapshotRow
	err := row.Scan(&i.CampaignID, &i.EmailCount)
	return i, err
}
