// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emails.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEmailByKey = `-- name: DeleteEmailByKey :exec
DELETE FROM emails
WHERE internal_id = $1
  AND fetched_at = $2
`

type DeleteEmailByKeyParams struct {
	InternalID int64              `db:"internal_id" json:"internal_id"`
	FetchedAt  pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
}

// Orphan cleanup: removes the emails row this ingestion inserted when it then
// lost the email_identities claim to a racing ingestion. Keyed on the composite
// partition key. Runs inside WithOrgTx so the RLS GUC scopes the delete.
func (q *Queries) DeleteEmailByKey(ctx context.Context, arg DeleteEmailByKeyParams) error {
	_, err := q.db.Exec(ctx, deleteEmailByKey, arg.InternalID, arg.FetchedAt)
	return err
}

const getEmailByInternalID = `-- name: GetEmailByInternalID :one
SELECT internal_id, fetched_at, message_id, campaign_id, sender_name, sender_email, sender_domain, reply_to_email, return_path, originating_ip, auth_spf, auth_dkim, auth_dmarc, auth_arc, x_originating_ip, mailer_agent, in_reply_to, references_list, content_charset, precedence, list_id, vendor_security_tags, subject, sent_timestamp, headers_json, body_plain, body_html, header_risk_score, content_risk_score, attachment_risk_score, url_risk_score, analysis_metadata, risk_score, deleted_at, org_id, current_verdict_label, updated_at, sent_at
FROM emails
WHERE internal_id = $1
  AND fetched_at = $2
  AND deleted_at IS NULL
`

type GetEmailByInternalIDParams struct {
	InternalID int64              `db:"internal_id" json:"internal_id"`
	FetchedAt  pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
}

// Reads a single email row by its composite partition key. org-scoped via RLS.
func (q *Queries) GetEmailByInternalID(ctx context.Context, arg GetEmailByInternalIDParams) (Email, error) {
	row := q.db.QueryRow(ctx, getEmailByInternalID, arg.InternalID, arg.FetchedAt)
	var i Email
	err := row.Scan(
		&i.InternalID,
		&i.FetchedAt,
		&i.MessageID,
		&i.CampaignID,
		&i.SenderName,
		&i.SenderEmail,
		&i.SenderDomain,
		&i.ReplyToEmail,
		&i.ReturnPath,
		&i.OriginatingIp,
		&i.AuthSpf,
		&i.AuthDkim,
		&i.AuthDmarc,
		&i.AuthArc,
		&i.XOriginatingIp,
		&i.MailerAgent,
		&i.InReplyTo,
		&i.ReferencesList,
		&i.ContentCharset,
		&i.Precedence,
		&i.ListID,
		&i.VendorSecurityTags,
		&i.Subject,
		&i.SentTimestamp,
		&i.HeadersJson,
		&i.BodyPlain,
		&i.BodyHtml,
		&i.HeaderRiskScore,
		&i.ContentRiskScore,
		&i.AttachmentRiskScore,
		&i.UrlRiskScore,
		&i.AnalysisMetadata,
		&i.RiskScore,
		&i.DeletedAt,
		&i.OrgID,
		&i.CurrentVerdictLabel,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const getEmailIdentity = `-- name: GetEmailIdentity :one
SELECT internal_id, fetched_at
FROM email_identities
WHERE org_id = $1
  AND message_id = $2
`

type GetEmailIdentityParams struct {
	OrgID     int64  `db:"org_id" json:"org_id"`
	MessageID string `db:"message_id" json:"message_id"`
}

type GetEmailIdentityRow struct {
	InternalID int64              `db:"internal_id" json:"internal_id"`
	FetchedAt  pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
}

// Looks up the canonical (internal_id, fetched_at) for an (org_id, message_id)
// pair in the cross-partition dedup registry. Runs inside WithOrgTx; the RLS
// GUC scopes the row. Returns no row when the message was never registered.
func (q *Queries) GetEmailIdentity(ctx context.Context, arg GetEmailIdentityParams) (GetEmailIdentityRow, error) {
	row := q.db.QueryRow(ctx, getEmailIdentity, arg.OrgID, arg.MessageID)
	var i GetEmailIdentityRow
	err := row.Scan(&i.InternalID, &i.FetchedAt)
	return i, err
}

const getEmailIdentityByEmailID = `-- name: GetEmailIdentityByEmailID :one
SELECT internal_id, fetched_at
FROM email_identities
WHERE org_id = $1
  AND email_id = $2
`

type GetEmailIdentityByEmailIDParams struct {
	OrgID   int64       `db:"org_id" json:"org_id"`
	EmailID pgtype.UUID `db:"email_id" json:"email_id"`
}

type GetEmailIdentityByEmailIDRow struct {
	InternalID int64              `db:"internal_id" json:"internal_id"`
	FetchedAt  pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
}

// Resolves the logical UUIDv7 email_id (G5/G17) back to the canonical
// (internal_id, fetched_at) partition key, so a caller holding only the opaque
// email_id (e.g. the svc-01 demo UI polling a verdict) can read the partitioned
// emails / verdict rows. email_id is stamped on the identity row by svc-02 at
// registration (migration 035). Runs inside WithOrgTx; the RLS GUC scopes the
// row. Returns no row for an unknown email_id or one registered before 035.
func (q *Queries) GetEmailIdentityByEmailID(ctx context.Context, arg GetEmailIdentityByEmailIDParams) (GetEmailIdentityByEmailIDRow, error) {
	row := q.db.QueryRow(ctx, getEmailIdentityByEmailID, arg.OrgID, arg.EmailID)
	var i GetEmailIdentityByEmailIDRow
	err := row.Scan(&i.InternalID, &i.FetchedAt)
	return i, err
}

const insertEmail = `-- name: InsertEmail :one

INSERT INTO emails (
    fetched_at,
    org_id,
    message_id,
    sender_name,
    sender_email,
    sender_domain,
    reply_to_email,
    return_path,
    originating_ip,
    auth_spf,
    auth_dkim,
    auth_dmarc,
    auth_arc,
    x_originating_ip,
    mailer_agent,
    in_reply_to,
    references_list,
    content_charset,
    precedence,
    list_id,
    vendor_security_tags,
    subject,
    sent_timestamp,
    headers_json,
    body_plain,
    body_html
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26
)
RETURNING internal_id, fetched_at
`

type InsertEmailParams struct {
	FetchedAt          pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
	OrgID              pgtype.Int8        `db:"org_id" json:"org_id"`
	MessageID          pgtype.Text        `db:"message_id" json:"message_id"`
	SenderName         pgtype.Text        `db:"sender_name" json:"sender_name"`
	SenderEmail        pgtype.Text        `db:"sender_email" json:"sender_email"`
	SenderDomain       pgtype.Text        `db:"sender_domain" json:"sender_domain"`
	ReplyToEmail       pgtype.Text        `db:"reply_to_email" json:"reply_to_email"`
	ReturnPath         pgtype.Text        `db:"return_path" json:"return_path"`
	OriginatingIp      *netip.Addr        `db:"originating_ip" json:"originating_ip"`
	AuthSpf            pgtype.Text        `db:"auth_spf" json:"auth_spf"`
	AuthDkim           pgtype.Text        `db:"auth_dkim" json:"auth_dkim"`
	AuthDmarc          pgtype.Text        `db:"auth_dmarc" json:"auth_dmarc"`
	AuthArc            pgtype.Text        `db:"auth_arc" json:"auth_arc"`
	XOriginatingIp     *netip.Addr        `db:"x_originating_ip" json:"x_originating_ip"`
	MailerAgent        pgtype.Text        `db:"mailer_agent" json:"mailer_agent"`
	InReplyTo          pgtype.Text        `db:"in_reply_to" json:"in_reply_to"`
	ReferencesList     []string           `db:"references_list" json:"references_list"`
	ContentCharset     pgtype.Text        `db:"content_charset" json:"content_charset"`
	Precedence         pgtype.Text        `db:"precedence" json:"precedence"`
	ListID             pgtype.Text        `db:"list_id" json:"list_id"`
	VendorSecurityTags []byte             `db:"vendor_security_tags" json:"vendor_security_tags"`
	Subject            pgtype.Text        `db:"subject" json:"subject"`
	SentTimestamp      pgtype.Int8        `db:"sent_timestamp" json:"sent_timestamp"`
	HeadersJson        []byte             `db:"headers_json" json:"headers_json"`
	BodyPlain          pgtype.Text        `db:"body_plain" json:"body_plain"`
	BodyHtml           pgtype.Text        `db:"body_html" json:"body_html"`
}

type InsertEmailRow struct {
	InternalID int64              `db:"internal_id" json:"internal_id"`
	FetchedAt  pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
}

// =============================================================================
// emails.sql — partitioned emails table writes owned by SVC-02 Parser
// =============================================================================
// See ARCH-SPEC §1 Step 2 and docs/internals for the parser persistence model.
//
// G5/G17 two-id model: the DB assigns internal_id (BIGSERIAL surrogate) and we
// RETURN it. The logical email_id is carried SEPARATELY on the wire — there is
// NO internal_id == email_id invariant. Callers must read the returned
// (internal_id, fetched_at) composite key and propagate it to the partitioned
// child tables (email_urls, email_attachments, email_recipients).
//
// RLS (spec §16 D12): emails has FORCE ROW LEVEL SECURITY; the surrounding
// transaction MUST issue `SET LOCAL app.current_org_id = <org>` (see the repo
// WithOrgTx helper) so org_id is checked against the tenant GUC on write.
// =============================================================================
// Inserts a freshly parsed email and returns the DB-assigned surrogate key
// plus the partition key needed by every downstream child-row insert.
// fetched_at is supplied by the caller (assigned at ingestion) so it stays
// stable across the whole persist transaction.
//
// Columns are exactly the set ARCH-SPEC §14 step 2 assigns to the parser
// (including x_originating_ip / content_charset / precedence / list_id /
// vendor_security_tags, which also ride analysis.headers). The score / verdict
// columns (risk_score, header/content/url/attachment_risk_score, campaign_id,
// analysis_metadata) are DELIBERATELY omitted — §14 step 2 keeps them at
// DEFAULT 0 / NULL until the Decision Engine UPDATEs them in step 5.
func (q *Queries) InsertEmail(ctx context.Context, arg InsertEmailParams) (InsertEmailRow, error) {
	row := q.db.QueryRow(ctx, insertEmail,
		arg.FetchedAt,
		arg.OrgID,
		arg.MessageID,
		arg.SenderName,
		arg.SenderEmail,
		arg.SenderDomain,
		arg.ReplyToEmail,
		arg.ReturnPath,
		arg.OriginatingIp,
		arg.AuthSpf,
		arg.AuthDkim,
		arg.AuthDmarc,
		arg.AuthArc,
		arg.XOriginatingIp,
		arg.MailerAgent,
		arg.InReplyTo,
		arg.ReferencesList,
		arg.ContentCharset,
		arg.Precedence,
		arg.ListID,
		arg.VendorSecurityTags,
		arg.Subject,
		arg.SentTimestamp,
		arg.HeadersJson,
		arg.BodyPlain,
		arg.BodyHtml,
	)
	var i InsertEmailRow
	err := row.Scan(&i.InternalID, &i.FetchedAt)
	return i, err
}

const registerEmailIdentity = `-- name: RegisterEmailIdentity :one
INSERT INTO email_identities (org_id, message_id, internal_id, fetched_at, email_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id, message_id) DO NOTHING
RETURNING internal_id
`

type RegisterEmailIdentityParams struct {
	OrgID      int64              `db:"org_id" json:"org_id"`
	MessageID  string             `db:"message_id" json:"message_id"`
	InternalID int64              `db:"internal_id" json:"internal_id"`
	FetchedAt  pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
	EmailID    pgtype.UUID        `db:"email_id" json:"email_id"`
}

// Claims (org_id, message_id) for this ingestion. ON CONFLICT DO NOTHING makes
// the claim atomic: a returned internal_id means we won the claim (new message),
// while no row means another ingestion already registered it (duplicate signal).
// email_id is the logical UUIDv7 (G5/G17), stamped here so the read side can map
// it back to (internal_id, fetched_at); it is NULL when the email carries no
// usable Message-ID (such emails are not registered). Runs inside WithOrgTx so
// the RLS GUC scopes the write.
func (q *Queries) RegisterEmailIdentity(ctx context.Context, arg RegisterEmailIdentityParams) (int64, error) {
	row := q.db.QueryRow(ctx, registerEmailIdentity,
		arg.OrgID,
		arg.MessageID,
		arg.InternalID,
		arg.FetchedAt,
		arg.EmailID,
	)
	var internal_id int64
	err := row.Scan(&internal_id)
	return internal_id, err
}
