// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_urls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEmailURL = `-- name: InsertEmailURL :one

INSERT INTO email_urls (
    email_id,
    email_fetched_at,
    threat_id,
    visible_text,
    org_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id
`

type InsertEmailURLParams struct {
	EmailID        int64              `db:"email_id" json:"email_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
	ThreatID       pgtype.Int8        `db:"threat_id" json:"threat_id"`
	VisibleText    pgtype.Text        `db:"visible_text" json:"visible_text"`
	OrgID          pgtype.Int8        `db:"org_id" json:"org_id"`
}

// =============================================================================
// email_urls.sql — URLs extracted from a parsed email (SVC-02 Parser)
// =============================================================================
// email_urls links an email (composite partition key internal_id, fetched_at)
// to the enriched_threats row for the URL, preserving the anchor visible_text.
// threat_id is nullable (ON DELETE SET NULL) so the email↔URL link survives a
// TI purge. org_id is set for RLS scoping.
// =============================================================================
// Appends one extracted URL for an email. Returns the row id so callers can
// record email_url_ti_matches against it.
func (q *Queries) InsertEmailURL(ctx context.Context, arg InsertEmailURLParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEmailURL,
		arg.EmailID,
		arg.EmailFetchedAt,
		arg.ThreatID,
		arg.VisibleText,
		arg.OrgID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listEmailURLs = `-- name: ListEmailURLs :many
SELECT id, threat_id, visible_text
FROM email_urls
WHERE email_id = $1
  AND email_fetched_at = $2
ORDER BY id
`

type ListEmailURLsParams struct {
	EmailID        int64              `db:"email_id" json:"email_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
}

type ListEmailURLsRow struct {
	ID          int64       `db:"id" json:"id"`
	ThreatID    pgtype.Int8 `db:"threat_id" json:"threat_id"`
	VisibleText pgtype.Text `db:"visible_text" json:"visible_text"`
}

// Lists URLs for an email by its composite partition key. org-scoped via RLS.
func (q *Queries) ListEmailURLs(ctx context.Context, arg ListEmailURLsParams) ([]ListEmailURLsRow, error) {
	rows, err := q.db.Query(ctx, listEmailURLs, arg.EmailID, arg.EmailFetchedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailURLsRow
	for rows.Next() {
		var i ListEmailURLsRow
		if err := rows.Scan(&i.ID, &i.ThreatID, &i.VisibleText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
