// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_attachments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEmailAttachment = `-- name: InsertEmailAttachment :exec

INSERT INTO email_attachments (
    email_id,
    email_fetched_at,
    attachment_id,
    filename,
    content_type,
    analysis_metadata,
    content_id,
    disposition,
    risk_score,
    org_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (email_id, email_fetched_at, attachment_id) DO NOTHING
`

type InsertEmailAttachmentParams struct {
	EmailID          int64              `db:"email_id" json:"email_id"`
	EmailFetchedAt   pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
	AttachmentID     int64              `db:"attachment_id" json:"attachment_id"`
	Filename         pgtype.Text        `db:"filename" json:"filename"`
	ContentType      pgtype.Text        `db:"content_type" json:"content_type"`
	AnalysisMetadata []byte             `db:"analysis_metadata" json:"analysis_metadata"`
	ContentID        pgtype.Text        `db:"content_id" json:"content_id"`
	Disposition      pgtype.Text        `db:"disposition" json:"disposition"`
	RiskScore        pgtype.Int4        `db:"risk_score" json:"risk_score"`
	OrgID            pgtype.Int8        `db:"org_id" json:"org_id"`
}

// =============================================================================
// email_attachments.sql — per-email attachment links (SVC-02 Parser)
// =============================================================================
// Links an email (composite partition key) to an attachment_library row by its
// content hash. Primary key is (email_id, email_fetched_at, attachment_id), so
// a re-parsed email re-attaching the same library entry is idempotent.
// =============================================================================
// Inserts one attachment link. ON CONFLICT DO NOTHING keeps the write
// idempotent across redelivery of the same parsed email.
func (q *Queries) InsertEmailAttachment(ctx context.Context, arg InsertEmailAttachmentParams) error {
	_, err := q.db.Exec(ctx, insertEmailAttachment,
		arg.EmailID,
		arg.EmailFetchedAt,
		arg.AttachmentID,
		arg.Filename,
		arg.ContentType,
		arg.AnalysisMetadata,
		arg.ContentID,
		arg.Disposition,
		arg.RiskScore,
		arg.OrgID,
	)
	return err
}

const listEmailAttachments = `-- name: ListEmailAttachments :many
SELECT attachment_id, filename, content_type, disposition, risk_score
FROM email_attachments
WHERE email_id = $1
  AND email_fetched_at = $2
ORDER BY attachment_id
`

type ListEmailAttachmentsParams struct {
	EmailID        int64              `db:"email_id" json:"email_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
}

type ListEmailAttachmentsRow struct {
	AttachmentID int64       `db:"attachment_id" json:"attachment_id"`
	Filename     pgtype.Text `db:"filename" json:"filename"`
	ContentType  pgtype.Text `db:"content_type" json:"content_type"`
	Disposition  pgtype.Text `db:"disposition" json:"disposition"`
	RiskScore    pgtype.Int4 `db:"risk_score" json:"risk_score"`
}

// Lists attachments for an email by composite partition key. org-scoped via RLS.
func (q *Queries) ListEmailAttachments(ctx context.Context, arg ListEmailAttachmentsParams) ([]ListEmailAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listEmailAttachments, arg.EmailID, arg.EmailFetchedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailAttachmentsRow
	for rows.Next() {
		var i ListEmailAttachmentsRow
		if err := rows.Scan(
			&i.AttachmentID,
			&i.Filename,
			&i.ContentType,
			&i.Disposition,
			&i.RiskScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
