// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_url_ti_matches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEmailURLTIMatch = `-- name: InsertEmailURLTIMatch :exec

INSERT INTO email_url_ti_matches (
    email_url_id,
    ti_indicator_id,
    match_type
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (email_url_id, ti_indicator_id) DO NOTHING
`

type InsertEmailURLTIMatchParams struct {
	EmailUrlID    int64  `db:"email_url_id" json:"email_url_id"`
	TiIndicatorID int64  `db:"ti_indicator_id" json:"ti_indicator_id"`
	MatchType     string `db:"match_type" json:"match_type"`
}

// =============================================================================
// email_url_ti_matches.sql — audit trail of TI feed matches against email URLs
// =============================================================================
// Records which ti_indicator was matched for each email_url and how. See the
// email_url_ti_matches table comment (migration 026). match_type is constrained
// to ('exact','domain','ip','cidr','hash'). The row is keyed UNIQUE on
// (email_url_id, ti_indicator_id).
//
// This table has no org_id column; isolation is inherited through the parent
// email_urls row (RLS-scoped) and the FK cascade.
// =============================================================================
// Records a TI match for an email URL. ON CONFLICT DO NOTHING keeps the audit
// write idempotent when the same indicator matches the same URL twice.
func (q *Queries) InsertEmailURLTIMatch(ctx context.Context, arg InsertEmailURLTIMatchParams) error {
	_, err := q.db.Exec(ctx, insertEmailURLTIMatch, arg.EmailUrlID, arg.TiIndicatorID, arg.MatchType)
	return err
}

const listEmailURLTIMatches = `-- name: ListEmailURLTIMatches :many
SELECT id, ti_indicator_id, match_type, matched_at
FROM email_url_ti_matches
WHERE email_url_id = $1
ORDER BY id
`

type ListEmailURLTIMatchesRow struct {
	ID            int64              `db:"id" json:"id"`
	TiIndicatorID int64              `db:"ti_indicator_id" json:"ti_indicator_id"`
	MatchType     string             `db:"match_type" json:"match_type"`
	MatchedAt     pgtype.Timestamptz `db:"matched_at" json:"matched_at"`
}

// Lists TI matches for a given email_url.
func (q *Queries) ListEmailURLTIMatches(ctx context.Context, emailUrlID int64) ([]ListEmailURLTIMatchesRow, error) {
	rows, err := q.db.Query(ctx, listEmailURLTIMatches, emailUrlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailURLTIMatchesRow
	for rows.Next() {
		var i ListEmailURLTIMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.TiIndicatorID,
			&i.MatchType,
			&i.MatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
