// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emails.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEmailByInternalID = `-- name: GetEmailByInternalID :one
SELECT internal_id, fetched_at, message_id, campaign_id, sender_name, sender_email, sender_domain, reply_to_email, return_path, originating_ip, auth_spf, auth_dkim, auth_dmarc, auth_arc, x_originating_ip, mailer_agent, in_reply_to, references_list, content_charset, precedence, list_id, vendor_security_tags, subject, sent_timestamp, headers_json, body_plain, body_html, header_risk_score, content_risk_score, attachment_risk_score, url_risk_score, analysis_metadata, risk_score, deleted_at, org_id, current_verdict_label, updated_at, sent_at
FROM emails
WHERE internal_id = $1
  AND fetched_at = $2
  AND deleted_at IS NULL
`

type GetEmailByInternalIDParams struct {
	InternalID int64              `db:"internal_id" json:"internal_id"`
	FetchedAt  pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
}

// Reads a single email row by its composite partition key. org-scoped via RLS.
func (q *Queries) GetEmailByInternalID(ctx context.Context, arg GetEmailByInternalIDParams) (Email, error) {
	row := q.db.QueryRow(ctx, getEmailByInternalID, arg.InternalID, arg.FetchedAt)
	var i Email
	err := row.Scan(
		&i.InternalID,
		&i.FetchedAt,
		&i.MessageID,
		&i.CampaignID,
		&i.SenderName,
		&i.SenderEmail,
		&i.SenderDomain,
		&i.ReplyToEmail,
		&i.ReturnPath,
		&i.OriginatingIp,
		&i.AuthSpf,
		&i.AuthDkim,
		&i.AuthDmarc,
		&i.AuthArc,
		&i.XOriginatingIp,
		&i.MailerAgent,
		&i.InReplyTo,
		&i.ReferencesList,
		&i.ContentCharset,
		&i.Precedence,
		&i.ListID,
		&i.VendorSecurityTags,
		&i.Subject,
		&i.SentTimestamp,
		&i.HeadersJson,
		&i.BodyPlain,
		&i.BodyHtml,
		&i.HeaderRiskScore,
		&i.ContentRiskScore,
		&i.AttachmentRiskScore,
		&i.UrlRiskScore,
		&i.AnalysisMetadata,
		&i.RiskScore,
		&i.DeletedAt,
		&i.OrgID,
		&i.CurrentVerdictLabel,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const insertEmail = `-- name: InsertEmail :one

INSERT INTO emails (
    fetched_at,
    org_id,
    message_id,
    sender_name,
    sender_email,
    sender_domain,
    reply_to_email,
    return_path,
    originating_ip,
    auth_spf,
    auth_dkim,
    auth_dmarc,
    auth_arc,
    mailer_agent,
    in_reply_to,
    references_list,
    subject,
    sent_timestamp,
    headers_json,
    body_plain,
    body_html,
    analysis_metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22
)
RETURNING internal_id, fetched_at
`

type InsertEmailParams struct {
	FetchedAt        pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
	OrgID            pgtype.Int8        `db:"org_id" json:"org_id"`
	MessageID        pgtype.Text        `db:"message_id" json:"message_id"`
	SenderName       pgtype.Text        `db:"sender_name" json:"sender_name"`
	SenderEmail      pgtype.Text        `db:"sender_email" json:"sender_email"`
	SenderDomain     pgtype.Text        `db:"sender_domain" json:"sender_domain"`
	ReplyToEmail     pgtype.Text        `db:"reply_to_email" json:"reply_to_email"`
	ReturnPath       pgtype.Text        `db:"return_path" json:"return_path"`
	OriginatingIp    *netip.Addr        `db:"originating_ip" json:"originating_ip"`
	AuthSpf          pgtype.Text        `db:"auth_spf" json:"auth_spf"`
	AuthDkim         pgtype.Text        `db:"auth_dkim" json:"auth_dkim"`
	AuthDmarc        pgtype.Text        `db:"auth_dmarc" json:"auth_dmarc"`
	AuthArc          pgtype.Text        `db:"auth_arc" json:"auth_arc"`
	MailerAgent      pgtype.Text        `db:"mailer_agent" json:"mailer_agent"`
	InReplyTo        pgtype.Text        `db:"in_reply_to" json:"in_reply_to"`
	ReferencesList   []string           `db:"references_list" json:"references_list"`
	Subject          pgtype.Text        `db:"subject" json:"subject"`
	SentTimestamp    pgtype.Int8        `db:"sent_timestamp" json:"sent_timestamp"`
	HeadersJson      []byte             `db:"headers_json" json:"headers_json"`
	BodyPlain        pgtype.Text        `db:"body_plain" json:"body_plain"`
	BodyHtml         pgtype.Text        `db:"body_html" json:"body_html"`
	AnalysisMetadata []byte             `db:"analysis_metadata" json:"analysis_metadata"`
}

type InsertEmailRow struct {
	InternalID int64              `db:"internal_id" json:"internal_id"`
	FetchedAt  pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
}

// =============================================================================
// emails.sql — partitioned emails table writes owned by SVC-02 Parser
// =============================================================================
// See ARCH-SPEC §1 Step 2 and docs/internals for the parser persistence model.
//
// G5/G17 two-id model: the DB assigns internal_id (BIGSERIAL surrogate) and we
// RETURN it. The logical email_id is carried SEPARATELY on the wire — there is
// NO internal_id == email_id invariant. Callers must read the returned
// (internal_id, fetched_at) composite key and propagate it to the partitioned
// child tables (email_urls, email_attachments, email_recipients).
//
// RLS (spec §16 D12): emails has FORCE ROW LEVEL SECURITY; the surrounding
// transaction MUST issue `SET LOCAL app.current_org_id = <org>` (see the repo
// WithOrgTx helper) so org_id is checked against the tenant GUC on write.
// =============================================================================
// Inserts a freshly parsed email and returns the DB-assigned surrogate key
// plus the partition key needed by every downstream child-row insert.
// fetched_at is supplied by the caller (assigned at ingestion) so it stays
// stable across the whole persist transaction.
func (q *Queries) InsertEmail(ctx context.Context, arg InsertEmailParams) (InsertEmailRow, error) {
	row := q.db.QueryRow(ctx, insertEmail,
		arg.FetchedAt,
		arg.OrgID,
		arg.MessageID,
		arg.SenderName,
		arg.SenderEmail,
		arg.SenderDomain,
		arg.ReplyToEmail,
		arg.ReturnPath,
		arg.OriginatingIp,
		arg.AuthSpf,
		arg.AuthDkim,
		arg.AuthDmarc,
		arg.AuthArc,
		arg.MailerAgent,
		arg.InReplyTo,
		arg.ReferencesList,
		arg.Subject,
		arg.SentTimestamp,
		arg.HeadersJson,
		arg.BodyPlain,
		arg.BodyHtml,
		arg.AnalysisMetadata,
	)
	var i InsertEmailRow
	err := row.Scan(&i.InternalID, &i.FetchedAt)
	return i, err
}
