// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emails_scores.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateEmailScores = `-- name: UpdateEmailScores :execrows

UPDATE emails
SET risk_score            = $3,
    header_risk_score     = $4,
    content_risk_score    = $5,
    url_risk_score        = $6,
    attachment_risk_score = $7,
    campaign_id           = $8,
    analysis_metadata     = COALESCE($9::jsonb, emails.analysis_metadata)
WHERE internal_id = $1 AND fetched_at = $2
`

type UpdateEmailScoresParams struct {
	InternalID          int64              `db:"internal_id" json:"internal_id"`
	FetchedAt           pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
	RiskScore           pgtype.Int4        `db:"risk_score" json:"risk_score"`
	HeaderRiskScore     pgtype.Int4        `db:"header_risk_score" json:"header_risk_score"`
	ContentRiskScore    pgtype.Int4        `db:"content_risk_score" json:"content_risk_score"`
	UrlRiskScore        pgtype.Int4        `db:"url_risk_score" json:"url_risk_score"`
	AttachmentRiskScore pgtype.Int4        `db:"attachment_risk_score" json:"attachment_risk_score"`
	CampaignID          pgtype.Int8        `db:"campaign_id" json:"campaign_id"`
	Column9             []byte             `db:"column_9" json:"column_9"`
}

// =============================================================================
// emails_scores.sql — emails risk-score updates owned by SVC-08 Decision Engine
// =============================================================================
// See ARCH-SPEC §1 Step 5 and docs/design/svc-07-08-design-brief.md §3.10.
// Updates the partitioned emails table by composite (internal_id, fetched_at)
// key.
// =============================================================================
// Sets the final risk scores and campaign linkage for a fully-scored email.
// analysis_metadata is JSONB; NULL keeps the existing value unchanged.
func (q *Queries) UpdateEmailScores(ctx context.Context, arg UpdateEmailScoresParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEmailScores,
		arg.InternalID,
		arg.FetchedAt,
		arg.RiskScore,
		arg.HeaderRiskScore,
		arg.ContentRiskScore,
		arg.UrlRiskScore,
		arg.AttachmentRiskScore,
		arg.CampaignID,
		arg.Column9,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
