// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrichment_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextEnrichmentJob = `-- name: ClaimNextEnrichmentJob :one
UPDATE enrichment_jobs
SET status = 'in_progress',
    locked_by = $1,
    attempts = attempts + 1,
    started_at = NOW()
WHERE id = (
    SELECT id
    FROM enrichment_jobs
    WHERE status = 'pending'
      AND deleted_at IS NULL
    ORDER BY priority DESC, created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, job_type, entity_type, entity_id, email_fetched_at, attempts, max_attempts
`

type ClaimNextEnrichmentJobRow struct {
	ID             int64              `db:"id" json:"id"`
	JobType        JobType            `db:"job_type" json:"job_type"`
	EntityType     EntityTypeEnum     `db:"entity_type" json:"entity_type"`
	EntityID       int64              `db:"entity_id" json:"entity_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
	Attempts       int32              `db:"attempts" json:"attempts"`
	MaxAttempts    int32              `db:"max_attempts" json:"max_attempts"`
}

// Atomically claims the highest-priority pending job for a worker using
// FOR UPDATE SKIP LOCKED, flipping it to in_progress and stamping the worker
// identity. Returns no rows when the queue is empty.
func (q *Queries) ClaimNextEnrichmentJob(ctx context.Context, lockedBy pgtype.Text) (ClaimNextEnrichmentJobRow, error) {
	row := q.db.QueryRow(ctx, claimNextEnrichmentJob, lockedBy)
	var i ClaimNextEnrichmentJobRow
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.EntityType,
		&i.EntityID,
		&i.EmailFetchedAt,
		&i.Attempts,
		&i.MaxAttempts,
	)
	return i, err
}

const completeEnrichmentJob = `-- name: CompleteEnrichmentJob :exec
UPDATE enrichment_jobs
SET status = 'completed',
    locked_by = NULL,
    completed_at = NOW()
WHERE id = $1
`

// Marks a claimed job as completed.
func (q *Queries) CompleteEnrichmentJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeEnrichmentJob, id)
	return err
}

const enqueueEnrichmentJob = `-- name: EnqueueEnrichmentJob :one

INSERT INTO enrichment_jobs (
    job_type,
    entity_type,
    entity_id,
    email_fetched_at,
    max_attempts,
    timeout_seconds,
    priority,
    org_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id
`

type EnqueueEnrichmentJobParams struct {
	JobType        JobType            `db:"job_type" json:"job_type"`
	EntityType     EntityTypeEnum     `db:"entity_type" json:"entity_type"`
	EntityID       int64              `db:"entity_id" json:"entity_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
	MaxAttempts    int32              `db:"max_attempts" json:"max_attempts"`
	TimeoutSeconds int32              `db:"timeout_seconds" json:"timeout_seconds"`
	Priority       int16              `db:"priority" json:"priority"`
	OrgID          pgtype.Int8        `db:"org_id" json:"org_id"`
}

// =============================================================================
// enrichment_jobs.sql — async enrichment work queue (SVC-03/04 workers)
// =============================================================================
// Workers claim pending jobs with SKIP LOCKED, run them, then mark complete or
// failed. org_id is set for RLS scoping; email_fetched_at carries the emails
// partition key when entity_type = 'email'. status/job_type are enum types.
// =============================================================================
// Enqueues a new enrichment job in the pending state. Returns the job id.
func (q *Queries) EnqueueEnrichmentJob(ctx context.Context, arg EnqueueEnrichmentJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, enqueueEnrichmentJob,
		arg.JobType,
		arg.EntityType,
		arg.EntityID,
		arg.EmailFetchedAt,
		arg.MaxAttempts,
		arg.TimeoutSeconds,
		arg.Priority,
		arg.OrgID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const failEnrichmentJob = `-- name: FailEnrichmentJob :exec
UPDATE enrichment_jobs
SET status = CASE WHEN attempts >= max_attempts THEN 'failed'::job_status
                  ELSE 'pending'::job_status END,
    locked_by = NULL,
    last_error = $2
WHERE id = $1
`

type FailEnrichmentJobParams struct {
	ID        int64       `db:"id" json:"id"`
	LastError pgtype.Text `db:"last_error" json:"last_error"`
}

// Marks a claimed job failed (or back to pending for retry when attempts remain),
// recording the error. Releases the worker lock either way.
func (q *Queries) FailEnrichmentJob(ctx context.Context, arg FailEnrichmentJobParams) error {
	_, err := q.db.Exec(ctx, failEnrichmentJob, arg.ID, arg.LastError)
	return err
}
