// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enriched_threats.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateEnrichedThreatEnrichment = `-- name: UpdateEnrichedThreatEnrichment :exec
UPDATE enriched_threats
SET
    online           = COALESCE($2, online),
    http_status_code = COALESCE($3, http_status_code),
    ip_address       = COALESCE($4, ip_address),
    cidr_block       = COALESCE($5, cidr_block),
    asn              = COALESCE($6, asn),
    asn_name         = COALESCE($7, asn_name),
    isp              = COALESCE($8, isp),
    country          = COALESCE($9, country),
    country_name     = COALESCE($10, country_name),
    region           = COALESCE($11, region),
    city             = COALESCE($12, city),
    latitude         = COALESCE($13, latitude),
    longitude        = COALESCE($14, longitude),
    ssl_enabled      = COALESCE($15, ssl_enabled),
    cert_issuer      = COALESCE($16, cert_issuer),
    cert_subject     = COALESCE($17, cert_subject),
    cert_valid_from  = COALESCE($18, cert_valid_from),
    cert_valid_to    = COALESCE($19, cert_valid_to),
    cert_serial      = COALESCE($20, cert_serial),
    registrar        = COALESCE($21, registrar),
    creation_date    = COALESCE($22, creation_date),
    expiry_date      = COALESCE($23, expiry_date),
    updated_date     = COALESCE($24, updated_date),
    name_servers     = COALESCE($25, name_servers),
    page_language    = COALESCE($26, page_language),
    page_title       = COALESCE($27, page_title),
    threat_type      = COALESCE($28, threat_type),
    risk_score       = COALESCE($29, risk_score),
    analysis_metadata = COALESCE($30::jsonb, analysis_metadata),
    last_checked     = NOW()
WHERE id = $1
`

type UpdateEnrichedThreatEnrichmentParams struct {
	ID             int64              `db:"id" json:"id"`
	Online         pgtype.Bool        `db:"online" json:"online"`
	HttpStatusCode pgtype.Int4        `db:"http_status_code" json:"http_status_code"`
	IpAddress      *netip.Addr        `db:"ip_address" json:"ip_address"`
	CidrBlock      pgtype.Text        `db:"cidr_block" json:"cidr_block"`
	Asn            pgtype.Int4        `db:"asn" json:"asn"`
	AsnName        pgtype.Text        `db:"asn_name" json:"asn_name"`
	Isp            pgtype.Text        `db:"isp" json:"isp"`
	Country        pgtype.Text        `db:"country" json:"country"`
	CountryName    pgtype.Text        `db:"country_name" json:"country_name"`
	Region         pgtype.Text        `db:"region" json:"region"`
	City           pgtype.Text        `db:"city" json:"city"`
	Latitude       pgtype.Float8      `db:"latitude" json:"latitude"`
	Longitude      pgtype.Float8      `db:"longitude" json:"longitude"`
	SslEnabled     pgtype.Bool        `db:"ssl_enabled" json:"ssl_enabled"`
	CertIssuer     pgtype.Text        `db:"cert_issuer" json:"cert_issuer"`
	CertSubject    pgtype.Text        `db:"cert_subject" json:"cert_subject"`
	CertValidFrom  pgtype.Timestamptz `db:"cert_valid_from" json:"cert_valid_from"`
	CertValidTo    pgtype.Timestamptz `db:"cert_valid_to" json:"cert_valid_to"`
	CertSerial     pgtype.Text        `db:"cert_serial" json:"cert_serial"`
	Registrar      pgtype.Text        `db:"registrar" json:"registrar"`
	CreationDate   pgtype.Date        `db:"creation_date" json:"creation_date"`
	ExpiryDate     pgtype.Date        `db:"expiry_date" json:"expiry_date"`
	UpdatedDate    pgtype.Date        `db:"updated_date" json:"updated_date"`
	NameServers    []string           `db:"name_servers" json:"name_servers"`
	PageLanguage   pgtype.Text        `db:"page_language" json:"page_language"`
	PageTitle      pgtype.Text        `db:"page_title" json:"page_title"`
	ThreatType     pgtype.Text        `db:"threat_type" json:"threat_type"`
	RiskScore      pgtype.Int4        `db:"risk_score" json:"risk_score"`
	Column30       []byte             `db:"column_30" json:"column_30"`
}

// Applies enrichment results to an existing threat row. Each parameter that is
// NULL leaves the corresponding column unchanged (COALESCE pattern), so a
// partial enricher (e.g. geo-only) does not clobber WHOIS data and vice versa.
func (q *Queries) UpdateEnrichedThreatEnrichment(ctx context.Context, arg UpdateEnrichedThreatEnrichmentParams) error {
	_, err := q.db.Exec(ctx, updateEnrichedThreatEnrichment,
		arg.ID,
		arg.Online,
		arg.HttpStatusCode,
		arg.IpAddress,
		arg.CidrBlock,
		arg.Asn,
		arg.AsnName,
		arg.Isp,
		arg.Country,
		arg.CountryName,
		arg.Region,
		arg.City,
		arg.Latitude,
		arg.Longitude,
		arg.SslEnabled,
		arg.CertIssuer,
		arg.CertSubject,
		arg.CertValidFrom,
		arg.CertValidTo,
		arg.CertSerial,
		arg.Registrar,
		arg.CreationDate,
		arg.ExpiryDate,
		arg.UpdatedDate,
		arg.NameServers,
		arg.PageLanguage,
		arg.PageTitle,
		arg.ThreatType,
		arg.RiskScore,
		arg.Column30,
	)
	return err
}

const upsertBareEnrichedThreat = `-- name: UpsertBareEnrichedThreat :one

INSERT INTO enriched_threats (
    url,
    domain,
    tld,
    org_id,
    is_global,
    first_seen,
    last_seen
) VALUES (
    $1,
    $2,
    $3,
    $4,
    FALSE,
    NOW(),
    NOW()
)
ON CONFLICT (url) DO UPDATE SET
    last_seen = NOW()
RETURNING id
`

type UpsertBareEnrichedThreatParams struct {
	Url    string      `db:"url" json:"url"`
	Domain pgtype.Text `db:"domain" json:"domain"`
	Tld    pgtype.Text `db:"tld" json:"tld"`
	OrgID  pgtype.Int8 `db:"org_id" json:"org_id"`
}

// =============================================================================
// enriched_threats.sql — email-observed URL/domain artefacts + enrichment
// =============================================================================
// See ARCH-SPEC §1 Step 2/3 and migration 026 table comment.
//
// Two write phases:
//  1. SVC-02 Parser UPSERTs a BARE row (url/domain/tld only) so it can take
//     the returned id as the email_urls.threat_id FK. The url column carries a
//     global UNIQUE constraint (enriched_threats_url_key), so the conflict
//     target is (url).
//  2. SVC-03/04 enrichers later UPDATE the same row in place with WHOIS, geo,
//     ASN, cert, page metadata, scoring, etc.
//
// enriched_threats has FORCE RLS with a policy that also admits is_global rows;
// the surrounding tx must set app.current_org_id (see WithOrgTx).
// =============================================================================
// Idempotent bare insert keyed on the global-unique url column. On conflict we
// only refresh last_seen and keep the existing enrichment untouched, so a
// re-observed URL never loses data populated by a later enrichment pass.
// Returns the row id used as email_urls.threat_id.
func (q *Queries) UpsertBareEnrichedThreat(ctx context.Context, arg UpsertBareEnrichedThreatParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertBareEnrichedThreat,
		arg.Url,
		arg.Domain,
		arg.Tld,
		arg.OrgID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
