// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package db

import (
	"context"
)

const getEnabledFeeds = `-- name: GetEnabledFeeds :many
SELECT id, name, display_name, feed_type, url, last_fetched_at, enabled, reliability_weight, created_at, updated_at, deleted_at
FROM feeds
WHERE enabled = TRUE
`

// SELECT * FROM feeds WHERE enabled = TRUE
func (q *Queries) GetEnabledFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.Query(ctx, getEnabledFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.FeedType,
			&i.Url,
			&i.LastFetchedAt,
			&i.Enabled,
			&i.ReliabilityWeight,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeedLastFetched = `-- name: UpdateFeedLastFetched :exec
UPDATE feeds
SET last_fetched_at = NOW()
WHERE id = $1
`

// UPDATE feeds SET last_fetched_at = NOW() WHERE id = $1
func (q *Queries) UpdateFeedLastFetched(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateFeedLastFetched, id)
	return err
}
