// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRuleHit = `-- name: InsertRuleHit :one
INSERT INTO rule_hits (
    rule_id,
    rule_version,
    entity_type,
    entity_id,
    email_fetched_at,
    score_impact,
    match_detail
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id
`

type InsertRuleHitParams struct {
	RuleID         pgtype.Int8        `db:"rule_id" json:"rule_id"`
	RuleVersion    string             `db:"rule_version" json:"rule_version"`
	EntityType     EntityTypeEnum     `db:"entity_type" json:"entity_type"`
	EntityID       int64              `db:"entity_id" json:"entity_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
	ScoreImpact    int32              `db:"score_impact" json:"score_impact"`
	MatchDetail    []byte             `db:"match_detail" json:"match_detail"`
}

// Records a single rule fire. entity_type / entity_id form a polymorphic
// pointer; SVC-04 always uses entity_type='email' + entity_id=emails.internal_id.
// score_impact and rule_version are denormalized snapshots; they must NOT be
// updated after insert (003 enrichments comment).
func (q *Queries) InsertRuleHit(ctx context.Context, arg InsertRuleHitParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRuleHit,
		arg.RuleID,
		arg.RuleVersion,
		arg.EntityType,
		arg.EntityID,
		arg.EmailFetchedAt,
		arg.ScoreImpact,
		arg.MatchDetail,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listActiveRulesForTargets = `-- name: ListActiveRulesForTargets :many

SELECT
    id,
    org_id,
    name,
    description,
    version,
    status,
    target,
    score_impact,
    logic,
    rule_group_id,
    created_at
FROM rules
WHERE status = 'active'
  AND target::text = ANY($1::text[])
  AND (org_id = $2 OR org_id IS NULL)
ORDER BY id
`

type ListActiveRulesForTargetsParams struct {
	Targets []string    `db:"targets" json:"targets"`
	OrgID   pgtype.Int8 `db:"org_id" json:"org_id"`
}

type ListActiveRulesForTargetsRow struct {
	ID          int64              `db:"id" json:"id"`
	OrgID       pgtype.Int8        `db:"org_id" json:"org_id"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	Version     string             `db:"version" json:"version"`
	Status      RuleStatus         `db:"status" json:"status"`
	Target      string             `db:"target" json:"target"`
	ScoreImpact int32              `db:"score_impact" json:"score_impact"`
	Logic       []byte             `db:"logic" json:"logic"`
	RuleGroupID pgtype.Int8        `db:"rule_group_id" json:"rule_group_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// =============================================================================
// rules.sql — queries for SVC-04 (Header) and SVC-08 (Decision Engine)
// =============================================================================
// See ARCH-SPEC §13 (table origin) and §14 step 3b.
// =============================================================================
// Returns every active rule whose target is in the given list (e.g. {'header','email'})
// and whose org scope either matches the caller or is global (org_id IS NULL).
// The (org_id IS NULL) branch lets a single SQL form serve both org-scoped
// and platform-wide rules.
func (q *Queries) ListActiveRulesForTargets(ctx context.Context, arg ListActiveRulesForTargetsParams) ([]ListActiveRulesForTargetsRow, error) {
	rows, err := q.db.Query(ctx, listActiveRulesForTargets, arg.Targets, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveRulesForTargetsRow
	for rows.Next() {
		var i ListActiveRulesForTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.Status,
			&i.Target,
			&i.ScoreImpact,
			&i.Logic,
			&i.RuleGroupID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
