// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: schema.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEmailByID = `-- name: GetEmailByID :one

SELECT internal_id, fetched_at, message_id, campaign_id, sender_name, sender_email, sender_domain, reply_to_email, return_path, originating_ip, auth_spf, auth_dkim, auth_dmarc, auth_arc, x_originating_ip, mailer_agent, in_reply_to, references_list, content_charset, precedence, list_id, vendor_security_tags, subject, sent_timestamp, headers_json, body_plain, body_html, header_risk_score, content_risk_score, attachment_risk_score, url_risk_score, analysis_metadata, risk_score, deleted_at, org_id, current_verdict_label, updated_at, sent_at FROM emails
WHERE internal_id = $1 AND fetched_at = $2 AND deleted_at IS NULL
`

type GetEmailByIDParams struct {
	InternalID int64              `db:"internal_id" json:"internal_id"`
	FetchedAt  pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
}

// Minimal query file for sqlc to generate structs from schema.
// sqlc automatically generates structs for all tables/views from migrations.
// Add domain-specific queries here as needed.
func (q *Queries) GetEmailByID(ctx context.Context, arg GetEmailByIDParams) (Email, error) {
	row := q.db.QueryRow(ctx, getEmailByID, arg.InternalID, arg.FetchedAt)
	var i Email
	err := row.Scan(
		&i.InternalID,
		&i.FetchedAt,
		&i.MessageID,
		&i.CampaignID,
		&i.SenderName,
		&i.SenderEmail,
		&i.SenderDomain,
		&i.ReplyToEmail,
		&i.ReturnPath,
		&i.OriginatingIp,
		&i.AuthSpf,
		&i.AuthDkim,
		&i.AuthDmarc,
		&i.AuthArc,
		&i.XOriginatingIp,
		&i.MailerAgent,
		&i.InReplyTo,
		&i.ReferencesList,
		&i.ContentCharset,
		&i.Precedence,
		&i.ListID,
		&i.VendorSecurityTags,
		&i.Subject,
		&i.SentTimestamp,
		&i.HeadersJson,
		&i.BodyPlain,
		&i.BodyHtml,
		&i.HeaderRiskScore,
		&i.ContentRiskScore,
		&i.AttachmentRiskScore,
		&i.UrlRiskScore,
		&i.AnalysisMetadata,
		&i.RiskScore,
		&i.DeletedAt,
		&i.OrgID,
		&i.CurrentVerdictLabel,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}
