// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCampaignSummary = `-- name: GetCampaignSummary :many
SELECT
    campaign_id,
    org_id,
    name,
    fingerprint,
    threat_type,
    target_brand,
    risk_score,
    first_seen,
    last_seen,
    email_count,
    COALESCE(avg_email_risk_score, 0)::float8 AS avg_email_risk_score,
    verdict_phishing,
    verdict_malware,
    verdict_suspicious,
    verdict_benign,
    verdict_spam,
    verdict_unknown
FROM mv_campaign_summary
WHERE org_id = $1
ORDER BY last_seen DESC NULLS LAST, campaign_id
`

type GetCampaignSummaryRow struct {
	CampaignID        int64              `db:"campaign_id" json:"campaign_id"`
	OrgID             pgtype.Int8        `db:"org_id" json:"org_id"`
	Name              string             `db:"name" json:"name"`
	Fingerprint       string             `db:"fingerprint" json:"fingerprint"`
	ThreatType        pgtype.Text        `db:"threat_type" json:"threat_type"`
	TargetBrand       pgtype.Text        `db:"target_brand" json:"target_brand"`
	RiskScore         pgtype.Int4        `db:"risk_score" json:"risk_score"`
	FirstSeen         pgtype.Timestamptz `db:"first_seen" json:"first_seen"`
	LastSeen          pgtype.Timestamptz `db:"last_seen" json:"last_seen"`
	EmailCount        int64              `db:"email_count" json:"email_count"`
	AvgEmailRiskScore float64            `db:"avg_email_risk_score" json:"avg_email_risk_score"`
	VerdictPhishing   int64              `db:"verdict_phishing" json:"verdict_phishing"`
	VerdictMalware    int64              `db:"verdict_malware" json:"verdict_malware"`
	VerdictSuspicious int64              `db:"verdict_suspicious" json:"verdict_suspicious"`
	VerdictBenign     int64              `db:"verdict_benign" json:"verdict_benign"`
	VerdictSpam       int64              `db:"verdict_spam" json:"verdict_spam"`
	VerdictUnknown    int64              `db:"verdict_unknown" json:"verdict_unknown"`
}

// mv_campaign_summary rows for the org's detected campaigns, newest activity
// first. org_id is nullable in the MV (COALESCE not applied); the explicit
// predicate is the tenant boundary.
func (q *Queries) GetCampaignSummary(ctx context.Context, orgID pgtype.Int8) ([]GetCampaignSummaryRow, error) {
	rows, err := q.db.Query(ctx, getCampaignSummary, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCampaignSummaryRow
	for rows.Next() {
		var i GetCampaignSummaryRow
		if err := rows.Scan(
			&i.CampaignID,
			&i.OrgID,
			&i.Name,
			&i.Fingerprint,
			&i.ThreatType,
			&i.TargetBrand,
			&i.RiskScore,
			&i.FirstSeen,
			&i.LastSeen,
			&i.EmailCount,
			&i.AvgEmailRiskScore,
			&i.VerdictPhishing,
			&i.VerdictMalware,
			&i.VerdictSuspicious,
			&i.VerdictBenign,
			&i.VerdictSpam,
			&i.VerdictUnknown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedHealth = `-- name: GetFeedHealth :many
SELECT
    feed_id,
    name,
    display_name,
    feed_type,
    reliability_weight,
    enabled,
    last_fetched_at,
    seconds_since_fetch,
    total_threats_contributed,
    active_threats,
    COALESCE(avg_threat_risk_score, 0)::float8 AS avg_threat_risk_score,
    most_recent_threat
FROM mv_feed_health
ORDER BY last_fetched_at DESC NULLS LAST, feed_id
`

type GetFeedHealthRow struct {
	FeedID                  int64              `db:"feed_id" json:"feed_id"`
	Name                    string             `db:"name" json:"name"`
	DisplayName             pgtype.Text        `db:"display_name" json:"display_name"`
	FeedType                string             `db:"feed_type" json:"feed_type"`
	ReliabilityWeight       float64            `db:"reliability_weight" json:"reliability_weight"`
	Enabled                 pgtype.Bool        `db:"enabled" json:"enabled"`
	LastFetchedAt           pgtype.Timestamptz `db:"last_fetched_at" json:"last_fetched_at"`
	SecondsSinceFetch       pgtype.Numeric     `db:"seconds_since_fetch" json:"seconds_since_fetch"`
	TotalThreatsContributed int64              `db:"total_threats_contributed" json:"total_threats_contributed"`
	ActiveThreats           int64              `db:"active_threats" json:"active_threats"`
	AvgThreatRiskScore      float64            `db:"avg_threat_risk_score" json:"avg_threat_risk_score"`
	MostRecentThreat        interface{}        `db:"most_recent_threat" json:"most_recent_threat"`
}

// mv_feed_health rows. Feeds are a PLATFORM-global resource (the MV has no org_id
// column), so this returns all feeds; ordering surfaces the freshest first.
func (q *Queries) GetFeedHealth(ctx context.Context) ([]GetFeedHealthRow, error) {
	rows, err := q.db.Query(ctx, getFeedHealth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedHealthRow
	for rows.Next() {
		var i GetFeedHealthRow
		if err := rows.Scan(
			&i.FeedID,
			&i.Name,
			&i.DisplayName,
			&i.FeedType,
			&i.ReliabilityWeight,
			&i.Enabled,
			&i.LastFetchedAt,
			&i.SecondsSinceFetch,
			&i.TotalThreatsContributed,
			&i.ActiveThreats,
			&i.AvgThreatRiskScore,
			&i.MostRecentThreat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrgIngestionSummary = `-- name: GetOrgIngestionSummary :one
SELECT
    org_id,
    total_emails,
    emails_last_24h,
    emails_last_7d,
    emails_last_30d,
    COALESCE(avg_risk_score, 0)::float8 AS avg_risk_score,
    max_risk_score,
    high_risk_count,
    medium_risk_count,
    low_risk_count,
    confirmed_phishing,
    confirmed_malware,
    confirmed_spam,
    confirmed_benign,
    unclassified
FROM mv_org_ingestion_summary
WHERE org_id = $1
`

type GetOrgIngestionSummaryRow struct {
	OrgID             pgtype.Int8 `db:"org_id" json:"org_id"`
	TotalEmails       int64       `db:"total_emails" json:"total_emails"`
	EmailsLast24h     int64       `db:"emails_last_24h" json:"emails_last_24h"`
	EmailsLast7d      int64       `db:"emails_last_7d" json:"emails_last_7d"`
	EmailsLast30d     int64       `db:"emails_last_30d" json:"emails_last_30d"`
	AvgRiskScore      float64     `db:"avg_risk_score" json:"avg_risk_score"`
	MaxRiskScore      interface{} `db:"max_risk_score" json:"max_risk_score"`
	HighRiskCount     int64       `db:"high_risk_count" json:"high_risk_count"`
	MediumRiskCount   int64       `db:"medium_risk_count" json:"medium_risk_count"`
	LowRiskCount      int64       `db:"low_risk_count" json:"low_risk_count"`
	ConfirmedPhishing int64       `db:"confirmed_phishing" json:"confirmed_phishing"`
	ConfirmedMalware  int64       `db:"confirmed_malware" json:"confirmed_malware"`
	ConfirmedSpam     int64       `db:"confirmed_spam" json:"confirmed_spam"`
	ConfirmedBenign   int64       `db:"confirmed_benign" json:"confirmed_benign"`
	Unclassified      int64       `db:"unclassified" json:"unclassified"`
}

// mv_org_ingestion_summary single row for the org's ingestion volumes + verdict
// breakdown. org_id is nullable in the MV. Returns no row when the org has
// ingested nothing yet (the console renders zeroes in that case).
func (q *Queries) GetOrgIngestionSummary(ctx context.Context, orgID pgtype.Int8) (GetOrgIngestionSummaryRow, error) {
	row := q.db.QueryRow(ctx, getOrgIngestionSummary, orgID)
	var i GetOrgIngestionSummaryRow
	err := row.Scan(
		&i.OrgID,
		&i.TotalEmails,
		&i.EmailsLast24h,
		&i.EmailsLast7d,
		&i.EmailsLast30d,
		&i.AvgRiskScore,
		&i.MaxRiskScore,
		&i.HighRiskCount,
		&i.MediumRiskCount,
		&i.LowRiskCount,
		&i.ConfirmedPhishing,
		&i.ConfirmedMalware,
		&i.ConfirmedSpam,
		&i.ConfirmedBenign,
		&i.Unclassified,
	)
	return i, err
}

const getRulePerformance = `-- name: GetRulePerformance :many
SELECT
    rule_id,
    org_id,
    name,
    version,
    status,
    target,
    score_impact,
    total_hits,
    hits_last_24h,
    hits_last_7d,
    COALESCE(total_score_contributed, 0)::bigint AS total_score_contributed,
    last_fired_at
FROM mv_rule_performance
WHERE org_id = $1 OR org_id IS NULL
ORDER BY total_hits DESC, rule_id
`

type GetRulePerformanceRow struct {
	RuleID                int64       `db:"rule_id" json:"rule_id"`
	OrgID                 pgtype.Int8 `db:"org_id" json:"org_id"`
	Name                  string      `db:"name" json:"name"`
	Version               string      `db:"version" json:"version"`
	Status                RuleStatus  `db:"status" json:"status"`
	Target                string      `db:"target" json:"target"`
	ScoreImpact           int32       `db:"score_impact" json:"score_impact"`
	TotalHits             int64       `db:"total_hits" json:"total_hits"`
	HitsLast24h           int64       `db:"hits_last_24h" json:"hits_last_24h"`
	HitsLast7d            int64       `db:"hits_last_7d" json:"hits_last_7d"`
	TotalScoreContributed int64       `db:"total_score_contributed" json:"total_score_contributed"`
	LastFiredAt           interface{} `db:"last_fired_at" json:"last_fired_at"`
}

// mv_rule_performance rows for the org's rules PLUS platform-global rules
// (org_id IS NULL). org_id is nullable in the MV.
func (q *Queries) GetRulePerformance(ctx context.Context, orgID pgtype.Int8) ([]GetRulePerformanceRow, error) {
	rows, err := q.db.Query(ctx, getRulePerformance, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRulePerformanceRow
	for rows.Next() {
		var i GetRulePerformanceRow
		if err := rows.Scan(
			&i.RuleID,
			&i.OrgID,
			&i.Name,
			&i.Version,
			&i.Status,
			&i.Target,
			&i.ScoreImpact,
			&i.TotalHits,
			&i.HitsLast24h,
			&i.HitsLast7d,
			&i.TotalScoreContributed,
			&i.LastFiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThreatSummary = `-- name: GetThreatSummary :many

SELECT
    threat_type,
    country,
    asn,
    asn_name,
    is_global,
    org_id,
    total,
    online_count,
    offline_count,
    COALESCE(avg_risk_score, 0)::float8 AS avg_risk_score,
    max_risk_score,
    earliest_seen,
    latest_seen
FROM mv_threat_summary
WHERE org_id = $1 OR is_global = TRUE
ORDER BY total DESC, threat_type
`

type GetThreatSummaryRow struct {
	ThreatType   string      `db:"threat_type" json:"threat_type"`
	Country      string      `db:"country" json:"country"`
	Asn          int32       `db:"asn" json:"asn"`
	AsnName      string      `db:"asn_name" json:"asn_name"`
	IsGlobal     bool        `db:"is_global" json:"is_global"`
	OrgID        int64       `db:"org_id" json:"org_id"`
	Total        int64       `db:"total" json:"total"`
	OnlineCount  int64       `db:"online_count" json:"online_count"`
	OfflineCount int64       `db:"offline_count" json:"offline_count"`
	AvgRiskScore float64     `db:"avg_risk_score" json:"avg_risk_score"`
	MaxRiskScore interface{} `db:"max_risk_score" json:"max_risk_score"`
	EarliestSeen interface{} `db:"earliest_seen" json:"earliest_seen"`
	LatestSeen   interface{} `db:"latest_seen" json:"latest_seen"`
}

// =============================================================================
// stats.sql — the 5 dashboard materialized-view reads for the svc-10 console
// (MVP-7 /stats). The MVs (mv_threat_summary, mv_campaign_summary,
// mv_feed_health, mv_rule_performance, mv_org_ingestion_summary) are rebuilt in
// migration 027. Materialized views are NOT RLS-forced — RLS does not propagate
// through a MV — so org scoping here is enforced by EXPLICIT org_id predicates in
// the SQL, NOT by the app.current_org_id GUC. The console passes the authenticated
// JWT claim OrgID as @org_id.
// =============================================================================
// mv_threat_summary grouped rows for the org's threat landscape. The MV stores
// org_id as COALESCE(org_id, -1) and a separate is_global flag; we return both
// the org's own rows AND globally-shared TI rows (is_global = TRUE), which is the
// intended cross-tenant TI corpus the analyst should see.
func (q *Queries) GetThreatSummary(ctx context.Context, orgID int64) ([]GetThreatSummaryRow, error) {
	rows, err := q.db.Query(ctx, getThreatSummary, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetThreatSummaryRow
	for rows.Next() {
		var i GetThreatSummaryRow
		if err := rows.Scan(
			&i.ThreatType,
			&i.Country,
			&i.Asn,
			&i.AsnName,
			&i.IsGlobal,
			&i.OrgID,
			&i.Total,
			&i.OnlineCount,
			&i.OfflineCount,
			&i.AvgRiskScore,
			&i.MaxRiskScore,
			&i.EarliestSeen,
			&i.LatestSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
