// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: svc02_emails.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEmail = `-- name: InsertEmail :execrows

INSERT INTO emails (
    internal_id, fetched_at, org_id,
    message_id,
    sender_name, sender_email, sender_domain, reply_to_email, return_path,
    auth_spf, auth_dkim, auth_dmarc, auth_arc,
    mailer_agent, in_reply_to, references_list,
    content_charset, precedence, list_id,
    subject, sent_timestamp, headers_json,
    body_plain, body_html
) VALUES (
    $1, $2, $3,
    $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16,
    $17, $18, $19,
    $20, $21, $22,
    $23, $24
)
ON CONFLICT (internal_id, fetched_at) DO NOTHING
`

type InsertEmailParams struct {
	InternalID     int64              `db:"internal_id" json:"internal_id"`
	FetchedAt      pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
	OrgID          pgtype.Int8        `db:"org_id" json:"org_id"`
	MessageID      pgtype.Text        `db:"message_id" json:"message_id"`
	SenderName     pgtype.Text        `db:"sender_name" json:"sender_name"`
	SenderEmail    pgtype.Text        `db:"sender_email" json:"sender_email"`
	SenderDomain   pgtype.Text        `db:"sender_domain" json:"sender_domain"`
	ReplyToEmail   pgtype.Text        `db:"reply_to_email" json:"reply_to_email"`
	ReturnPath     pgtype.Text        `db:"return_path" json:"return_path"`
	AuthSpf        pgtype.Text        `db:"auth_spf" json:"auth_spf"`
	AuthDkim       pgtype.Text        `db:"auth_dkim" json:"auth_dkim"`
	AuthDmarc      pgtype.Text        `db:"auth_dmarc" json:"auth_dmarc"`
	AuthArc        pgtype.Text        `db:"auth_arc" json:"auth_arc"`
	MailerAgent    pgtype.Text        `db:"mailer_agent" json:"mailer_agent"`
	InReplyTo      pgtype.Text        `db:"in_reply_to" json:"in_reply_to"`
	ReferencesList []string           `db:"references_list" json:"references_list"`
	ContentCharset pgtype.Text        `db:"content_charset" json:"content_charset"`
	Precedence     pgtype.Text        `db:"precedence" json:"precedence"`
	ListID         pgtype.Text        `db:"list_id" json:"list_id"`
	Subject        pgtype.Text        `db:"subject" json:"subject"`
	SentTimestamp  pgtype.Int8        `db:"sent_timestamp" json:"sent_timestamp"`
	HeadersJson    []byte             `db:"headers_json" json:"headers_json"`
	BodyPlain      pgtype.Text        `db:"body_plain" json:"body_plain"`
	BodyHtml       pgtype.Text        `db:"body_html" json:"body_html"`
}

// =============================================================================
// svc02_emails.sql — email persistence owned by SVC-02 Parser
// =============================================================================
// One transaction per email writes the canonical emails row plus its junction
// tables. SVC-02 sets internal_id explicitly to the logical email_id carried on
// the Kafka envelope so SVC-08's later UPDATE … WHERE internal_id = $1 hits this
// exact row (ARCH-SPEC §1 step 2, §14 step 2). Score/campaign/metadata columns
// are left at defaults — the Decision Engine fills them.
// =============================================================================
// Inserts the canonical email row with an explicit internal_id (= envelope
// email_id) and fetched_at, which together form the partition key. ON CONFLICT
// DO NOTHING makes redelivery of the same Kafka message idempotent; the writer
// uses the returned row count to skip junction writes when the row already
// existed (avoiding duplicate email_urls / email_attachments PK conflicts).
func (q *Queries) InsertEmail(ctx context.Context, arg InsertEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEmail,
		arg.InternalID,
		arg.FetchedAt,
		arg.OrgID,
		arg.MessageID,
		arg.SenderName,
		arg.SenderEmail,
		arg.SenderDomain,
		arg.ReplyToEmail,
		arg.ReturnPath,
		arg.AuthSpf,
		arg.AuthDkim,
		arg.AuthDmarc,
		arg.AuthArc,
		arg.MailerAgent,
		arg.InReplyTo,
		arg.ReferencesList,
		arg.ContentCharset,
		arg.Precedence,
		arg.ListID,
		arg.Subject,
		arg.SentTimestamp,
		arg.HeadersJson,
		arg.BodyPlain,
		arg.BodyHtml,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertEmailAttachment = `-- name: InsertEmailAttachment :exec
INSERT INTO email_attachments (
    email_id, email_fetched_at, attachment_id,
    filename, content_type, content_id, disposition, org_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertEmailAttachmentParams struct {
	EmailID        int64              `db:"email_id" json:"email_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
	AttachmentID   int64              `db:"attachment_id" json:"attachment_id"`
	Filename       pgtype.Text        `db:"filename" json:"filename"`
	ContentType    pgtype.Text        `db:"content_type" json:"content_type"`
	ContentID      pgtype.Text        `db:"content_id" json:"content_id"`
	Disposition    pgtype.Text        `db:"disposition" json:"disposition"`
	OrgID          pgtype.Int8        `db:"org_id" json:"org_id"`
}

// Records one attachment occurrence on an email, joined to attachment_library.
func (q *Queries) InsertEmailAttachment(ctx context.Context, arg InsertEmailAttachmentParams) error {
	_, err := q.db.Exec(ctx, insertEmailAttachment,
		arg.EmailID,
		arg.EmailFetchedAt,
		arg.AttachmentID,
		arg.Filename,
		arg.ContentType,
		arg.ContentID,
		arg.Disposition,
		arg.OrgID,
	)
	return err
}

const insertEmailRecipient = `-- name: InsertEmailRecipient :exec
INSERT INTO email_recipients (
    email_id, email_fetched_at, org_id, address, display_name, recipient_type
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertEmailRecipientParams struct {
	EmailID        int64              `db:"email_id" json:"email_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
	OrgID          pgtype.Int8        `db:"org_id" json:"org_id"`
	Address        string             `db:"address" json:"address"`
	DisplayName    pgtype.Text        `db:"display_name" json:"display_name"`
	RecipientType  string             `db:"recipient_type" json:"recipient_type"`
}

// Records one To/Cc/Bcc recipient of an email.
func (q *Queries) InsertEmailRecipient(ctx context.Context, arg InsertEmailRecipientParams) error {
	_, err := q.db.Exec(ctx, insertEmailRecipient,
		arg.EmailID,
		arg.EmailFetchedAt,
		arg.OrgID,
		arg.Address,
		arg.DisplayName,
		arg.RecipientType,
	)
	return err
}

const insertEmailURL = `-- name: InsertEmailURL :exec
INSERT INTO email_urls (email_id, email_fetched_at, threat_id, visible_text, org_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEmailURLParams struct {
	EmailID        int64              `db:"email_id" json:"email_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
	ThreatID       pgtype.Int8        `db:"threat_id" json:"threat_id"`
	VisibleText    pgtype.Text        `db:"visible_text" json:"visible_text"`
	OrgID          pgtype.Int8        `db:"org_id" json:"org_id"`
}

// Links an email to an enriched_threats row, preserving the anchor visible text.
func (q *Queries) InsertEmailURL(ctx context.Context, arg InsertEmailURLParams) error {
	_, err := q.db.Exec(ctx, insertEmailURL,
		arg.EmailID,
		arg.EmailFetchedAt,
		arg.ThreatID,
		arg.VisibleText,
		arg.OrgID,
	)
	return err
}

const upsertAttachmentLibrary = `-- name: UpsertAttachmentLibrary :one
INSERT INTO attachment_library (sha256, md5, sha1, size_bytes, entropy, actual_extension)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (sha256) DO UPDATE
SET md5              = COALESCE(EXCLUDED.md5, attachment_library.md5),
    sha1             = COALESCE(EXCLUDED.sha1, attachment_library.sha1),
    size_bytes       = COALESCE(EXCLUDED.size_bytes, attachment_library.size_bytes),
    entropy          = COALESCE(EXCLUDED.entropy, attachment_library.entropy),
    actual_extension = COALESCE(EXCLUDED.actual_extension, attachment_library.actual_extension)
RETURNING id
`

type UpsertAttachmentLibraryParams struct {
	Sha256          string        `db:"sha256" json:"sha256"`
	Md5             pgtype.Text   `db:"md5" json:"md5"`
	Sha1            pgtype.Text   `db:"sha1" json:"sha1"`
	SizeBytes       pgtype.Int8   `db:"size_bytes" json:"size_bytes"`
	Entropy         pgtype.Float8 `db:"entropy" json:"entropy"`
	ActualExtension pgtype.Text   `db:"actual_extension" json:"actual_extension"`
}

// Deduplicates attachment binaries by sha256 (global, cross-tenant) and returns
// the library id for the email_attachments FK.
func (q *Queries) UpsertAttachmentLibrary(ctx context.Context, arg UpsertAttachmentLibraryParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertAttachmentLibrary,
		arg.Sha256,
		arg.Md5,
		arg.Sha1,
		arg.SizeBytes,
		arg.Entropy,
		arg.ActualExtension,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertEnrichedThreatBare = `-- name: UpsertEnrichedThreatBare :one
INSERT INTO enriched_threats (url, domain, tld, source_feed, is_global)
VALUES ($1, $2, $3, 'email', TRUE)
ON CONFLICT (url) DO UPDATE
SET domain    = COALESCE(EXCLUDED.domain, enriched_threats.domain),
    tld       = COALESCE(EXCLUDED.tld, enriched_threats.tld),
    last_seen = NOW()
RETURNING id
`

type UpsertEnrichedThreatBareParams struct {
	Url    string      `db:"url" json:"url"`
	Domain pgtype.Text `db:"domain" json:"domain"`
	Tld    pgtype.Text `db:"tld" json:"tld"`
}

// Ensures a bare enriched_threats row exists for a URL and returns its id for
// the email_urls.threat_id FK. Enrichment columns are filled later by SVC-03.
// source_feed='email' + is_global=TRUE satisfy the table's two CHECK constraints
// (chk_enriched_threats_feed_or_source and chk_enriched_threats_global_or_org)
// for an email-observed row; url is globally unique, so the enrichment record is
// shared and the per-tenant link lives on email_urls.org_id.
func (q *Queries) UpsertEnrichedThreatBare(ctx context.Context, arg UpsertEnrichedThreatBareParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertEnrichedThreatBare, arg.Url, arg.Domain, arg.Tld)
	var id int64
	err := row.Scan(&id)
	return id, err
}
