// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: svc05_attachments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAttachmentBySHA256 = `-- name: GetAttachmentBySHA256 :one

SELECT id, is_malicious, entropy, actual_extension, size_bytes
FROM attachment_library
WHERE sha256 = $1
`

type GetAttachmentBySHA256Row struct {
	ID              int64         `db:"id" json:"id"`
	IsMalicious     pgtype.Bool   `db:"is_malicious" json:"is_malicious"`
	Entropy         pgtype.Float8 `db:"entropy" json:"entropy"`
	ActualExtension pgtype.Text   `db:"actual_extension" json:"actual_extension"`
	SizeBytes       pgtype.Int8   `db:"size_bytes" json:"size_bytes"`
}

// =============================================================================
// svc05_attachments.sql — attachment scoring lookups owned by SVC-05
// =============================================================================
// SVC-05 resolves each attachment's library row by sha256 (for the malicious
// short-circuit + entropy/magic-byte heuristics + the attachment_id needed to
// write the per-email score back), then UPDATEs email_attachments.risk_score.
// ARCH-SPEC Step 3c, §15 Gap #2.
// =============================================================================
// Returns the library row used to score an attachment. SVC-02 inserts this row
// before publishing analysis.attachments, so it exists at consume time.
func (q *Queries) GetAttachmentBySHA256(ctx context.Context, sha256 string) (GetAttachmentBySHA256Row, error) {
	row := q.db.QueryRow(ctx, getAttachmentBySHA256, sha256)
	var i GetAttachmentBySHA256Row
	err := row.Scan(
		&i.ID,
		&i.IsMalicious,
		&i.Entropy,
		&i.ActualExtension,
		&i.SizeBytes,
	)
	return i, err
}

const updateEmailAttachmentRiskScore = `-- name: UpdateEmailAttachmentRiskScore :exec
UPDATE email_attachments
SET risk_score = $4
WHERE email_id = $1 AND email_fetched_at = $2 AND attachment_id = $3
`

type UpdateEmailAttachmentRiskScoreParams struct {
	EmailID        int64              `db:"email_id" json:"email_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
	AttachmentID   int64              `db:"attachment_id" json:"attachment_id"`
	RiskScore      pgtype.Int4        `db:"risk_score" json:"risk_score"`
}

// Writes the scored risk back to the per-email attachment occurrence.
func (q *Queries) UpdateEmailAttachmentRiskScore(ctx context.Context, arg UpdateEmailAttachmentRiskScoreParams) error {
	_, err := q.db.Exec(ctx, updateEmailAttachmentRiskScore,
		arg.EmailID,
		arg.EmailFetchedAt,
		arg.AttachmentID,
		arg.RiskScore,
	)
	return err
}
