// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: svc09_notification.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrgNotificationConfig = `-- name: GetOrgNotificationConfig :one

SELECT notification_threshold, notification_channels
FROM organisations
WHERE id = $1 AND deleted_at IS NULL
`

type GetOrgNotificationConfigRow struct {
	NotificationThreshold pgtype.Int4 `db:"notification_threshold" json:"notification_threshold"`
	NotificationChannels  []byte      `db:"notification_channels" json:"notification_channels"`
}

// =============================================================================
// svc09_notification.sql — notification config + recipient lookups (SVC-09)
// =============================================================================
// SVC-09 reads per-org notification preferences (migration 030) and resolves
// admin recipients when the email channel is enabled. ARCH-SPEC Step 6a.
// =============================================================================
// Returns the org's notify threshold + enabled channels. NULLs fall back to the
// column defaults (70 / ["webhook"]) in the caller.
func (q *Queries) GetOrgNotificationConfig(ctx context.Context, id int64) (GetOrgNotificationConfigRow, error) {
	row := q.db.QueryRow(ctx, getOrgNotificationConfig, id)
	var i GetOrgNotificationConfigRow
	err := row.Scan(&i.NotificationThreshold, &i.NotificationChannels)
	return i, err
}

const listOrgAdminEmails = `-- name: ListOrgAdminEmails :many
SELECT email
FROM users
WHERE org_id = $1 AND role = 'admin'::user_role AND deleted_at IS NULL
`

// Email recipients for the 'email' channel: active admin users of the org.
func (q *Queries) ListOrgAdminEmails(ctx context.Context, orgID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listOrgAdminEmails, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
