// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: svc03_enrichment.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEnrichedThreatByURL = `-- name: GetEnrichedThreatByURL :one
SELECT id, last_checked, risk_score
FROM enriched_threats
WHERE url = $1
`

type GetEnrichedThreatByURLRow struct {
	ID          int64              `db:"id" json:"id"`
	LastChecked pgtype.Timestamptz `db:"last_checked" json:"last_checked"`
	RiskScore   pgtype.Int4        `db:"risk_score" json:"risk_score"`
}

// Prior-email reuse: returns the enrichment freshness + score for a URL already
// seen on a previous email, so a still-fresh row can be reused without a refetch.
func (q *Queries) GetEnrichedThreatByURL(ctx context.Context, url string) (GetEnrichedThreatByURLRow, error) {
	row := q.db.QueryRow(ctx, getEnrichedThreatByURL, url)
	var i GetEnrichedThreatByURLRow
	err := row.Scan(&i.ID, &i.LastChecked, &i.RiskScore)
	return i, err
}

const insertEmailURLTIMatch = `-- name: InsertEmailURLTIMatch :exec
INSERT INTO email_url_ti_matches (email_url_id, ti_indicator_id, match_type)
VALUES ($1, $2, 'domain')
ON CONFLICT (email_url_id, ti_indicator_id) DO NOTHING
`

type InsertEmailURLTIMatchParams struct {
	EmailUrlID    int64 `db:"email_url_id" json:"email_url_id"`
	TiIndicatorID int64 `db:"ti_indicator_id" json:"ti_indicator_id"`
}

// Audit row linking an email URL to the TI indicator that matched it.
func (q *Queries) InsertEmailURLTIMatch(ctx context.Context, arg InsertEmailURLTIMatchParams) error {
	_, err := q.db.Exec(ctx, insertEmailURLTIMatch, arg.EmailUrlID, arg.TiIndicatorID)
	return err
}

const insertEnrichmentJob = `-- name: InsertEnrichmentJob :exec
INSERT INTO enrichment_jobs (job_type, status, entity_type, entity_id, started_at, completed_at)
VALUES ('url_scan'::job_type, 'completed'::job_status, 'threat', $1, NOW(), NOW())
`

// Logs a completed synchronous url_scan enrichment job for the threat entity.
func (q *Queries) InsertEnrichmentJob(ctx context.Context, entityID int64) error {
	_, err := q.db.Exec(ctx, insertEnrichmentJob, entityID)
	return err
}

const listEmailURLsForEmail = `-- name: ListEmailURLsForEmail :many

SELECT eu.id AS email_url_id, eu.threat_id, et.url
FROM email_urls eu
JOIN enriched_threats et ON et.id = eu.threat_id
WHERE eu.email_id = $1 AND eu.email_fetched_at = $2
`

type ListEmailURLsForEmailParams struct {
	EmailID        int64              `db:"email_id" json:"email_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
}

type ListEmailURLsForEmailRow struct {
	EmailUrlID int64       `db:"email_url_id" json:"email_url_id"`
	ThreatID   pgtype.Int8 `db:"threat_id" json:"threat_id"`
	Url        string      `db:"url" json:"url"`
}

// =============================================================================
// svc03_enrichment.sql — URL enrichment persistence owned by SVC-03 URL Analysis
// =============================================================================
// After scoring an email's URLs, SVC-03 enriches each one and persists the
// result: it UPDATEs the bare enriched_threats row SVC-02 created, records the
// per-provider raw response in enrichment_results, logs an enrichment_jobs row,
// and writes an email_url_ti_matches audit row for every TI-feed hit.
// ARCH-SPEC §1 step 3a, §14 step 3a.
// =============================================================================
// Maps each URL of an email to its email_urls.id and enriched_threats.id, so
// SVC-03 can attach enrichment and TI-match rows to the SVC-02-created rows.
func (q *Queries) ListEmailURLsForEmail(ctx context.Context, arg ListEmailURLsForEmailParams) ([]ListEmailURLsForEmailRow, error) {
	rows, err := q.db.Query(ctx, listEmailURLsForEmail, arg.EmailID, arg.EmailFetchedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailURLsForEmailRow
	for rows.Next() {
		var i ListEmailURLsForEmailRow
		if err := rows.Scan(&i.EmailUrlID, &i.ThreatID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnrichedThreatEnrichment = `-- name: UpdateEnrichedThreatEnrichment :exec
UPDATE enriched_threats
SET online           = $2,
    http_status_code = $3,
    ip_address       = $4,
    cidr_block       = $5,
    asn              = $6,
    asn_name         = $7,
    isp              = $8,
    country          = $9,
    country_name     = $10,
    region           = $11,
    city             = $12,
    latitude         = $13,
    longitude        = $14,
    ssl_enabled      = $15,
    cert_issuer      = $16,
    cert_subject     = $17,
    cert_valid_from  = $18,
    cert_valid_to    = $19,
    registrar        = $20,
    creation_date    = $21,
    expiry_date      = $22,
    updated_date     = $23,
    name_servers     = $24,
    page_language    = $25,
    page_title       = $26,
    risk_score       = $27,
    last_checked     = NOW(),
    last_seen        = NOW()
WHERE id = $1
`

type UpdateEnrichedThreatEnrichmentParams struct {
	ID             int64              `db:"id" json:"id"`
	Online         pgtype.Bool        `db:"online" json:"online"`
	HttpStatusCode pgtype.Int4        `db:"http_status_code" json:"http_status_code"`
	IpAddress      *netip.Addr        `db:"ip_address" json:"ip_address"`
	CidrBlock      pgtype.Text        `db:"cidr_block" json:"cidr_block"`
	Asn            pgtype.Int4        `db:"asn" json:"asn"`
	AsnName        pgtype.Text        `db:"asn_name" json:"asn_name"`
	Isp            pgtype.Text        `db:"isp" json:"isp"`
	Country        pgtype.Text        `db:"country" json:"country"`
	CountryName    pgtype.Text        `db:"country_name" json:"country_name"`
	Region         pgtype.Text        `db:"region" json:"region"`
	City           pgtype.Text        `db:"city" json:"city"`
	Latitude       pgtype.Float8      `db:"latitude" json:"latitude"`
	Longitude      pgtype.Float8      `db:"longitude" json:"longitude"`
	SslEnabled     pgtype.Bool        `db:"ssl_enabled" json:"ssl_enabled"`
	CertIssuer     pgtype.Text        `db:"cert_issuer" json:"cert_issuer"`
	CertSubject    pgtype.Text        `db:"cert_subject" json:"cert_subject"`
	CertValidFrom  pgtype.Timestamptz `db:"cert_valid_from" json:"cert_valid_from"`
	CertValidTo    pgtype.Timestamptz `db:"cert_valid_to" json:"cert_valid_to"`
	Registrar      pgtype.Text        `db:"registrar" json:"registrar"`
	CreationDate   pgtype.Date        `db:"creation_date" json:"creation_date"`
	ExpiryDate     pgtype.Date        `db:"expiry_date" json:"expiry_date"`
	UpdatedDate    pgtype.Date        `db:"updated_date" json:"updated_date"`
	NameServers    []string           `db:"name_servers" json:"name_servers"`
	PageLanguage   pgtype.Text        `db:"page_language" json:"page_language"`
	PageTitle      pgtype.Text        `db:"page_title" json:"page_title"`
	RiskScore      pgtype.Int4        `db:"risk_score" json:"risk_score"`
}

// Fills the bare enriched_threats row with live enrichment (DNS/IP geo, TLS,
// WHOIS, HTTP) and refreshes the freshness timestamps.
func (q *Queries) UpdateEnrichedThreatEnrichment(ctx context.Context, arg UpdateEnrichedThreatEnrichmentParams) error {
	_, err := q.db.Exec(ctx, updateEnrichedThreatEnrichment,
		arg.ID,
		arg.Online,
		arg.HttpStatusCode,
		arg.IpAddress,
		arg.CidrBlock,
		arg.Asn,
		arg.AsnName,
		arg.Isp,
		arg.Country,
		arg.CountryName,
		arg.Region,
		arg.City,
		arg.Latitude,
		arg.Longitude,
		arg.SslEnabled,
		arg.CertIssuer,
		arg.CertSubject,
		arg.CertValidFrom,
		arg.CertValidTo,
		arg.Registrar,
		arg.CreationDate,
		arg.ExpiryDate,
		arg.UpdatedDate,
		arg.NameServers,
		arg.PageLanguage,
		arg.PageTitle,
		arg.RiskScore,
	)
	return err
}

const upsertEnrichmentResult = `-- name: UpsertEnrichmentResult :exec
INSERT INTO enrichment_results (
    entity_type, entity_id, provider, raw_response, ttl_seconds, reputation_score
) VALUES ('threat', $1, $2, $3, $4, $5)
ON CONFLICT (entity_type, entity_id, provider) DO UPDATE
SET raw_response     = EXCLUDED.raw_response,
    ttl_seconds      = EXCLUDED.ttl_seconds,
    reputation_score = EXCLUDED.reputation_score,
    fetched_at       = NOW()
`

type UpsertEnrichmentResultParams struct {
	EntityID        int64         `db:"entity_id" json:"entity_id"`
	Provider        string        `db:"provider" json:"provider"`
	RawResponse     []byte        `db:"raw_response" json:"raw_response"`
	TtlSeconds      pgtype.Int4   `db:"ttl_seconds" json:"ttl_seconds"`
	ReputationScore pgtype.Float8 `db:"reputation_score" json:"reputation_score"`
}

// Stores one provider's raw response keyed (entity_type, entity_id, provider).
// ttl_seconds drives the compute_expires_at trigger; setting fetched_at=NOW()
// on conflict refreshes expires_at so stale rows re-fetch correctly.
func (q *Queries) UpsertEnrichmentResult(ctx context.Context, arg UpsertEnrichmentResultParams) error {
	_, err := q.db.Exec(ctx, upsertEnrichmentResult,
		arg.EntityID,
		arg.Provider,
		arg.RawResponse,
		arg.TtlSeconds,
		arg.ReputationScore,
	)
	return err
}
