// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: svc10_dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEmailForOrg = `-- name: GetEmailForOrg :one
SELECT internal_id, fetched_at, message_id, sender_name, sender_email, sender_domain,
       reply_to_email, return_path, subject, auth_spf, auth_dkim, auth_dmarc,
       header_risk_score, content_risk_score, attachment_risk_score, url_risk_score,
       risk_score, current_verdict_label, campaign_id
FROM emails
WHERE internal_id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type GetEmailForOrgParams struct {
	InternalID int64       `db:"internal_id" json:"internal_id"`
	OrgID      pgtype.Int8 `db:"org_id" json:"org_id"`
}

type GetEmailForOrgRow struct {
	InternalID          int64              `db:"internal_id" json:"internal_id"`
	FetchedAt           pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
	MessageID           pgtype.Text        `db:"message_id" json:"message_id"`
	SenderName          pgtype.Text        `db:"sender_name" json:"sender_name"`
	SenderEmail         pgtype.Text        `db:"sender_email" json:"sender_email"`
	SenderDomain        pgtype.Text        `db:"sender_domain" json:"sender_domain"`
	ReplyToEmail        pgtype.Text        `db:"reply_to_email" json:"reply_to_email"`
	ReturnPath          pgtype.Text        `db:"return_path" json:"return_path"`
	Subject             pgtype.Text        `db:"subject" json:"subject"`
	AuthSpf             pgtype.Text        `db:"auth_spf" json:"auth_spf"`
	AuthDkim            pgtype.Text        `db:"auth_dkim" json:"auth_dkim"`
	AuthDmarc           pgtype.Text        `db:"auth_dmarc" json:"auth_dmarc"`
	HeaderRiskScore     pgtype.Int4        `db:"header_risk_score" json:"header_risk_score"`
	ContentRiskScore    pgtype.Int4        `db:"content_risk_score" json:"content_risk_score"`
	AttachmentRiskScore pgtype.Int4        `db:"attachment_risk_score" json:"attachment_risk_score"`
	UrlRiskScore        pgtype.Int4        `db:"url_risk_score" json:"url_risk_score"`
	RiskScore           pgtype.Int4        `db:"risk_score" json:"risk_score"`
	CurrentVerdictLabel pgtype.Text        `db:"current_verdict_label" json:"current_verdict_label"`
	CampaignID          pgtype.Int8        `db:"campaign_id" json:"campaign_id"`
}

// Scan detail header (org-scoped so one tenant can't read another's email).
func (q *Queries) GetEmailForOrg(ctx context.Context, arg GetEmailForOrgParams) (GetEmailForOrgRow, error) {
	row := q.db.QueryRow(ctx, getEmailForOrg, arg.InternalID, arg.OrgID)
	var i GetEmailForOrgRow
	err := row.Scan(
		&i.InternalID,
		&i.FetchedAt,
		&i.MessageID,
		&i.SenderName,
		&i.SenderEmail,
		&i.SenderDomain,
		&i.ReplyToEmail,
		&i.ReturnPath,
		&i.Subject,
		&i.AuthSpf,
		&i.AuthDkim,
		&i.AuthDmarc,
		&i.HeaderRiskScore,
		&i.ContentRiskScore,
		&i.AttachmentRiskScore,
		&i.UrlRiskScore,
		&i.RiskScore,
		&i.CurrentVerdictLabel,
		&i.CampaignID,
	)
	return i, err
}

const getOrgStats = `-- name: GetOrgStats :one
SELECT
    count(*)                                                  AS total,
    count(*) FILTER (WHERE current_verdict_label = 'phishing')   AS phishing,
    count(*) FILTER (WHERE current_verdict_label = 'suspicious') AS suspicious,
    count(*) FILTER (WHERE risk_score >= 70)                  AS high_risk,
    count(*) FILTER (WHERE fetched_at >= NOW() - INTERVAL '24 hours') AS last_24h
FROM emails
WHERE org_id = $1 AND deleted_at IS NULL
`

type GetOrgStatsRow struct {
	Total      int64 `db:"total" json:"total"`
	Phishing   int64 `db:"phishing" json:"phishing"`
	Suspicious int64 `db:"suspicious" json:"suspicious"`
	HighRisk   int64 `db:"high_risk" json:"high_risk"`
	Last24h    int64 `db:"last_24h" json:"last_24h"`
}

// Headline dashboard counters for an org.
func (q *Queries) GetOrgStats(ctx context.Context, orgID pgtype.Int8) (GetOrgStatsRow, error) {
	row := q.db.QueryRow(ctx, getOrgStats, orgID)
	var i GetOrgStatsRow
	err := row.Scan(
		&i.Total,
		&i.Phishing,
		&i.Suspicious,
		&i.HighRisk,
		&i.Last24h,
	)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one

SELECT id, org_id, email, role, password_hash
FROM users
WHERE email = $1 AND deleted_at IS NULL
LIMIT 1
`

type GetUserForLoginRow struct {
	ID           int64       `db:"id" json:"id"`
	OrgID        int64       `db:"org_id" json:"org_id"`
	Email        string      `db:"email" json:"email"`
	Role         UserRole    `db:"role" json:"role"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
}

// =============================================================================
// svc10_dashboard.sql — read + auth queries for the SVC-10 API/dashboard
// =============================================================================
// All list/detail reads are org-scoped (the org_id comes from the caller's JWT).
// ARCH-SPEC Step 6b.
// =============================================================================
// Resolves a login by email (emails are unique per org; LIMIT 1 covers the rare
// cross-org duplicate). Returns the bcrypt hash for verification.
func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
	)
	return i, err
}

const listCampaignsByOrg = `-- name: ListCampaignsByOrg :many
SELECT id, name, fingerprint, threat_type, target_brand, risk_score, first_seen, last_seen
FROM campaigns
WHERE org_id = $1 AND deleted_at IS NULL
ORDER BY last_seen DESC NULLS LAST
LIMIT $2
`

type ListCampaignsByOrgParams struct {
	OrgID pgtype.Int8 `db:"org_id" json:"org_id"`
	Limit int32       `db:"limit" json:"limit"`
}

type ListCampaignsByOrgRow struct {
	ID          int64              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Fingerprint string             `db:"fingerprint" json:"fingerprint"`
	ThreatType  pgtype.Text        `db:"threat_type" json:"threat_type"`
	TargetBrand pgtype.Text        `db:"target_brand" json:"target_brand"`
	RiskScore   pgtype.Int4        `db:"risk_score" json:"risk_score"`
	FirstSeen   pgtype.Timestamptz `db:"first_seen" json:"first_seen"`
	LastSeen    pgtype.Timestamptz `db:"last_seen" json:"last_seen"`
}

func (q *Queries) ListCampaignsByOrg(ctx context.Context, arg ListCampaignsByOrgParams) ([]ListCampaignsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listCampaignsByOrg, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignsByOrgRow
	for rows.Next() {
		var i ListCampaignsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Fingerprint,
			&i.ThreatType,
			&i.TargetBrand,
			&i.RiskScore,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailAttachmentsForDetail = `-- name: ListEmailAttachmentsForDetail :many
SELECT ea.attachment_id, ea.filename, ea.content_type, ea.risk_score,
       al.sha256, al.is_malicious, al.actual_extension
FROM email_attachments ea
JOIN attachment_library al ON al.id = ea.attachment_id
WHERE ea.email_id = $1
`

type ListEmailAttachmentsForDetailRow struct {
	AttachmentID    int64       `db:"attachment_id" json:"attachment_id"`
	Filename        pgtype.Text `db:"filename" json:"filename"`
	ContentType     pgtype.Text `db:"content_type" json:"content_type"`
	RiskScore       pgtype.Int4 `db:"risk_score" json:"risk_score"`
	Sha256          string      `db:"sha256" json:"sha256"`
	IsMalicious     pgtype.Bool `db:"is_malicious" json:"is_malicious"`
	ActualExtension pgtype.Text `db:"actual_extension" json:"actual_extension"`
}

func (q *Queries) ListEmailAttachmentsForDetail(ctx context.Context, emailID int64) ([]ListEmailAttachmentsForDetailRow, error) {
	rows, err := q.db.Query(ctx, listEmailAttachmentsForDetail, emailID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailAttachmentsForDetailRow
	for rows.Next() {
		var i ListEmailAttachmentsForDetailRow
		if err := rows.Scan(
			&i.AttachmentID,
			&i.Filename,
			&i.ContentType,
			&i.RiskScore,
			&i.Sha256,
			&i.IsMalicious,
			&i.ActualExtension,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailRecipientsForDetail = `-- name: ListEmailRecipientsForDetail :many
SELECT address, display_name, recipient_type
FROM email_recipients
WHERE email_id = $1
`

type ListEmailRecipientsForDetailRow struct {
	Address       string      `db:"address" json:"address"`
	DisplayName   pgtype.Text `db:"display_name" json:"display_name"`
	RecipientType string      `db:"recipient_type" json:"recipient_type"`
}

func (q *Queries) ListEmailRecipientsForDetail(ctx context.Context, emailID int64) ([]ListEmailRecipientsForDetailRow, error) {
	rows, err := q.db.Query(ctx, listEmailRecipientsForDetail, emailID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailRecipientsForDetailRow
	for rows.Next() {
		var i ListEmailRecipientsForDetailRow
		if err := rows.Scan(&i.Address, &i.DisplayName, &i.RecipientType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailURLsForDetail = `-- name: ListEmailURLsForDetail :many
SELECT eu.id, et.url, eu.visible_text, et.domain, et.risk_score, et.threat_type
FROM email_urls eu
JOIN enriched_threats et ON et.id = eu.threat_id
WHERE eu.email_id = $1
`

type ListEmailURLsForDetailRow struct {
	ID          int64       `db:"id" json:"id"`
	Url         string      `db:"url" json:"url"`
	VisibleText pgtype.Text `db:"visible_text" json:"visible_text"`
	Domain      pgtype.Text `db:"domain" json:"domain"`
	RiskScore   pgtype.Int4 `db:"risk_score" json:"risk_score"`
	ThreatType  pgtype.Text `db:"threat_type" json:"threat_type"`
}

func (q *Queries) ListEmailURLsForDetail(ctx context.Context, emailID int64) ([]ListEmailURLsForDetailRow, error) {
	rows, err := q.db.Query(ctx, listEmailURLsForDetail, emailID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailURLsForDetailRow
	for rows.Next() {
		var i ListEmailURLsForDetailRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.VisibleText,
			&i.Domain,
			&i.RiskScore,
			&i.ThreatType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailVerdicts = `-- name: ListEmailVerdicts :many
SELECT label, confidence, source, model_version, created_at
FROM verdicts
WHERE entity_type = 'email' AND entity_id = $1
ORDER BY created_at DESC
`

type ListEmailVerdictsRow struct {
	Label        VerdictLabel       `db:"label" json:"label"`
	Confidence   pgtype.Float8      `db:"confidence" json:"confidence"`
	Source       VerdictSource      `db:"source" json:"source"`
	ModelVersion pgtype.Text        `db:"model_version" json:"model_version"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListEmailVerdicts(ctx context.Context, entityID int64) ([]ListEmailVerdictsRow, error) {
	rows, err := q.db.Query(ctx, listEmailVerdicts, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailVerdictsRow
	for rows.Next() {
		var i ListEmailVerdictsRow
		if err := rows.Scan(
			&i.Label,
			&i.Confidence,
			&i.Source,
			&i.ModelVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailsByOrg = `-- name: ListEmailsByOrg :many
SELECT internal_id, fetched_at, sender_email, sender_domain, subject,
       risk_score, current_verdict_label
FROM emails
WHERE org_id = $1 AND deleted_at IS NULL
ORDER BY fetched_at DESC
LIMIT $2 OFFSET $3
`

type ListEmailsByOrgParams struct {
	OrgID  pgtype.Int8 `db:"org_id" json:"org_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type ListEmailsByOrgRow struct {
	InternalID          int64              `db:"internal_id" json:"internal_id"`
	FetchedAt           pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
	SenderEmail         pgtype.Text        `db:"sender_email" json:"sender_email"`
	SenderDomain        pgtype.Text        `db:"sender_domain" json:"sender_domain"`
	Subject             pgtype.Text        `db:"subject" json:"subject"`
	RiskScore           pgtype.Int4        `db:"risk_score" json:"risk_score"`
	CurrentVerdictLabel pgtype.Text        `db:"current_verdict_label" json:"current_verdict_label"`
}

// Paged scan list with the denormalised current verdict label + final score.
func (q *Queries) ListEmailsByOrg(ctx context.Context, arg ListEmailsByOrgParams) ([]ListEmailsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listEmailsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailsByOrgRow
	for rows.Next() {
		var i ListEmailsByOrgRow
		if err := rows.Scan(
			&i.InternalID,
			&i.FetchedAt,
			&i.SenderEmail,
			&i.SenderDomain,
			&i.Subject,
			&i.RiskScore,
			&i.CurrentVerdictLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchUserLastLogin = `-- name: TouchUserLastLogin :exec
UPDATE users SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) TouchUserLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchUserLastLogin, id)
	return err
}
