// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ti_indicators.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateStaleFeedIndicators = `-- name: DeactivateStaleFeedIndicators :execrows
UPDATE ti_indicators
SET
    is_active = FALSE,
    updated_at = CURRENT_TIMESTAMP
WHERE feed_id = $1
  AND is_active = TRUE
  AND (last_seen IS NULL OR last_seen < $2)
`

type DeactivateStaleFeedIndicatorsParams struct {
	FeedID   int64              `db:"feed_id" json:"feed_id"`
	LastSeen pgtype.Timestamptz `db:"last_seen" json:"last_seen"`
}

// Sets is_active = FALSE for indicators belonging to feed_id
// not seen since the cutoff timestamp.
func (q *Queries) DeactivateStaleFeedIndicators(ctx context.Context, arg DeactivateStaleFeedIndicatorsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateStaleFeedIndicators, arg.FeedID, arg.LastSeen)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveDomainIndicators = `-- name: ListActiveDomainIndicators :many
SELECT
    id,
    indicator_value,
    risk_score,
    threat_type
FROM ti_indicators
WHERE indicator_type = 'domain'
  AND is_active = TRUE
`

type ListActiveDomainIndicatorsRow struct {
	ID             int64       `db:"id" json:"id"`
	IndicatorValue string      `db:"indicator_value" json:"indicator_value"`
	RiskScore      int32       `db:"risk_score" json:"risk_score"`
	ThreatType     pgtype.Text `db:"threat_type" json:"threat_type"`
}

// SELECT id, indicator_value, risk_score, threat_type
// FROM ti_indicators WHERE indicator_type = 'domain' AND is_active = TRUE
func (q *Queries) ListActiveDomainIndicators(ctx context.Context) ([]ListActiveDomainIndicatorsRow, error) {
	rows, err := q.db.Query(ctx, listActiveDomainIndicators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveDomainIndicatorsRow
	for rows.Next() {
		var i ListActiveDomainIndicatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.IndicatorValue,
			&i.RiskScore,
			&i.ThreatType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTIIndicator = `-- name: UpsertTIIndicator :one
INSERT INTO ti_indicators (
    feed_id,
    indicator_type,
    indicator_value,
    threat_type,
    brand_id,
    target_brand,
    threat_tags,
    source_id,
    first_seen,
    last_seen,
    confidence,
    risk_score,
    is_active,
    raw_metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
ON CONFLICT (feed_id, indicator_type, indicator_value)
DO UPDATE
SET
    last_seen = EXCLUDED.last_seen,
    threat_tags = (
        SELECT ARRAY(
            SELECT DISTINCT tag
            FROM unnest(
                COALESCE(ti_indicators.threat_tags, '{}'::TEXT[]) ||
                COALESCE(EXCLUDED.threat_tags, '{}'::TEXT[])
            ) AS tag
            WHERE tag IS NOT NULL
              AND btrim(tag) <> ''
            ORDER BY tag
        )
    ),
    risk_score = GREATEST(ti_indicators.risk_score, EXCLUDED.risk_score)
RETURNING (xmax = 0) AS inserted
`

type UpsertTIIndicatorParams struct {
	FeedID         int64              `db:"feed_id" json:"feed_id"`
	IndicatorType  TiIndicatorType    `db:"indicator_type" json:"indicator_type"`
	IndicatorValue string             `db:"indicator_value" json:"indicator_value"`
	ThreatType     pgtype.Text        `db:"threat_type" json:"threat_type"`
	BrandID        pgtype.Int8        `db:"brand_id" json:"brand_id"`
	TargetBrand    pgtype.Text        `db:"target_brand" json:"target_brand"`
	ThreatTags     []string           `db:"threat_tags" json:"threat_tags"`
	SourceID       pgtype.Text        `db:"source_id" json:"source_id"`
	FirstSeen      pgtype.Timestamptz `db:"first_seen" json:"first_seen"`
	LastSeen       pgtype.Timestamptz `db:"last_seen" json:"last_seen"`
	Confidence     pgtype.Float8      `db:"confidence" json:"confidence"`
	RiskScore      int32              `db:"risk_score" json:"risk_score"`
	IsActive       bool               `db:"is_active" json:"is_active"`
	RawMetadata    []byte             `db:"raw_metadata" json:"raw_metadata"`
}

// Upserts a single TI indicator. Use with batch loop from Go for chunk processing.
// ON CONFLICT (feed_id, indicator_type, indicator_value):
//
//	update last_seen, merge threat_tags (distinct), GREATEST risk_score.
//	Do NOT overwrite first_seen or created_at.
//
// Returns TRUE when the row was newly inserted, FALSE when an existing row was updated.
func (q *Queries) UpsertTIIndicator(ctx context.Context, arg UpsertTIIndicatorParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertTIIndicator,
		arg.FeedID,
		arg.IndicatorType,
		arg.IndicatorValue,
		arg.ThreatType,
		arg.BrandID,
		arg.TargetBrand,
		arg.ThreatTags,
		arg.SourceID,
		arg.FirstSeen,
		arg.LastSeen,
		arg.Confidence,
		arg.RiskScore,
		arg.IsActive,
		arg.RawMetadata,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}
