// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verdicts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findExistingVerdictForEmail = `-- name: FindExistingVerdictForEmail :one
SELECT id, COALESCE(kafka_verdict_wire::text, '') AS kafka_wire
FROM verdicts
WHERE entity_type = $1::entity_type_enum
  AND entity_id = $2
  AND email_fetched_at IS NOT NULL
  AND email_fetched_at = $3::timestamptz
LIMIT 1
`

type FindExistingVerdictForEmailParams struct {
	Column1  EntityTypeEnum     `db:"column_1" json:"column_1"`
	EntityID int64              `db:"entity_id" json:"entity_id"`
	Column3  pgtype.Timestamptz `db:"column_3" json:"column_3"`
}

type FindExistingVerdictForEmailRow struct {
	ID        int64       `db:"id" json:"id"`
	KafkaWire interface{} `db:"kafka_wire" json:"kafka_wire"`
}

// Idempotency probe for SVC-08 replay: returns the verdict already recorded for
// this email partition key plus its stored kafka_verdict_wire (as text) so the
// engine can republish byte-for-byte without recomputing. Returns no rows on
// first processing.
func (q *Queries) FindExistingVerdictForEmail(ctx context.Context, arg FindExistingVerdictForEmailParams) (FindExistingVerdictForEmailRow, error) {
	row := q.db.QueryRow(ctx, findExistingVerdictForEmail, arg.Column1, arg.EntityID, arg.Column3)
	var i FindExistingVerdictForEmailRow
	err := row.Scan(&i.ID, &i.KafkaWire)
	return i, err
}

const insertVerdict = `-- name: InsertVerdict :one

INSERT INTO verdicts (
    entity_type,
    entity_id,
    email_fetched_at,
    label,
    confidence,
    source,
    model_version,
    org_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id
`

type InsertVerdictParams struct {
	EntityType     EntityTypeEnum     `db:"entity_type" json:"entity_type"`
	EntityID       int64              `db:"entity_id" json:"entity_id"`
	EmailFetchedAt pgtype.Timestamptz `db:"email_fetched_at" json:"email_fetched_at"`
	Label          VerdictLabel       `db:"label" json:"label"`
	Confidence     pgtype.Float8      `db:"confidence" json:"confidence"`
	Source         VerdictSource      `db:"source" json:"source"`
	ModelVersion   pgtype.Text        `db:"model_version" json:"model_version"`
	OrgID          pgtype.Int8        `db:"org_id" json:"org_id"`
}

// =============================================================================
// verdicts.sql — queries for SVC-08 Decision Engine
// =============================================================================
// See ARCH-SPEC §1 Step 5 and docs/design/svc-07-08-design-brief.md §3.10.
// The verdicts table is APPEND-ONLY: never UPDATE / DELETE a verdict row.
// =============================================================================
// Records a single verdict for an email (entity_type='email').
// entity_id  = emails.internal_id
// email_fetched_at = emails.fetched_at (required for partitioned-table joins;
//
//	see migration 014_fix_polymorphic_email_key).
//
// source must be one of the verdict_source enum values: model | analyst | feed | rule.
func (q *Queries) InsertVerdict(ctx context.Context, arg InsertVerdictParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertVerdict,
		arg.EntityType,
		arg.EntityID,
		arg.EmailFetchedAt,
		arg.Label,
		arg.Confidence,
		arg.Source,
		arg.ModelVersion,
		arg.OrgID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateVerdictKafkaWire = `-- name: UpdateVerdictKafkaWire :exec
UPDATE verdicts SET kafka_verdict_wire = $1::jsonb WHERE id = $2
`

type UpdateVerdictKafkaWireParams struct {
	Column1 []byte `db:"column_1" json:"column_1"`
	ID      int64  `db:"id" json:"id"`
}

// Persists the emails.verdict JSON written for this verdict so redelivery can
// republish identical bytes. Written in the same tx as the verdict insert.
func (q *Queries) UpdateVerdictKafkaWire(ctx context.Context, arg UpdateVerdictKafkaWireParams) error {
	_, err := q.db.Exec(ctx, updateVerdictKafkaWire, arg.Column1, arg.ID)
	return err
}
